-- AI Agent、提示词、会话与模型配置表。
-- 仅包含当前版本完整表结构；全新数据库第一个执行。

CREATE TABLE IF NOT EXISTS ai_model_config (
    id BIGINT NOT NULL COMMENT '主键',
    create_by BIGINT NOT NULL DEFAULT 0 COMMENT '创建人用户 ID',
    update_by BIGINT NOT NULL DEFAULT 0 COMMENT '更新人用户 ID',
    name VARCHAR(100) NOT NULL COMMENT '配置名称',
    provider VARCHAR(50) NOT NULL COMMENT '供应商编码，例如 deepseek、kimi',
    model_name VARCHAR(100) NOT NULL COMMENT '模型名称',
    base_url VARCHAR(255) NOT NULL COMMENT '模型服务 Base URL',
    chat_path VARCHAR(120) NOT NULL DEFAULT '/chat/completions' COMMENT 'Chat Completions 路径',
    api_key TEXT NOT NULL COMMENT '加密 API Key，格式 enc:v1:<iv>.<ciphertext>',
    enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
    is_default TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否默认配置',
    sequence INT NOT NULL DEFAULT 0 COMMENT '优先级，数字越小越优先',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    KEY idx_ai_model_config_provider (provider, enabled, deleted),
    KEY idx_ai_model_config_priority (enabled, deleted, is_default, sequence)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI 模型配置';

CREATE TABLE IF NOT EXISTS ai_agent (
    id BIGINT NOT NULL COMMENT '主键',
    create_by BIGINT NOT NULL DEFAULT 0 COMMENT '创建人用户 ID',
    update_by BIGINT NOT NULL DEFAULT 0 COMMENT '更新人用户 ID',
    name VARCHAR(100) NOT NULL COMMENT 'Agent 名称',
    code VARCHAR(50) NOT NULL COMMENT 'Agent 唯一编码',
    type VARCHAR(20) NOT NULL DEFAULT 'chat' COMMENT '类型：chat、analysis、assistant',
    icon VARCHAR(200) DEFAULT NULL COMMENT '图标编码',
    description VARCHAR(500) DEFAULT NULL COMMENT '功能描述',
    system_prompt TEXT COMMENT '完整系统提示词',
    concise_prompt TEXT COMMENT '多轮对话精简提示词',
    welcome_message VARCHAR(500) DEFAULT NULL COMMENT '欢迎语',
    model_config_id BIGINT DEFAULT NULL COMMENT '绑定的具体模型配置 ID',
    model_provider VARCHAR(50) DEFAULT NULL COMMENT '指定模型供应商',
    model_name VARCHAR(100) DEFAULT NULL COMMENT '指定模型名称',
    temperature DECIMAL(4,2) DEFAULT NULL COMMENT '温度参数',
    max_tokens INT DEFAULT NULL COMMENT '最大输出 Token 数',
    preset_commands JSON COMMENT '预设指令 JSON',
    enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
    sequence INT NOT NULL DEFAULT 0 COMMENT '排序号',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_agent_code (code),
    KEY idx_ai_agent_type (type),
    KEY idx_ai_agent_enabled (enabled, deleted, sequence),
    KEY idx_ai_agent_model_config (model_config_id, deleted),
    CONSTRAINT fk_ai_agent_model_config FOREIGN KEY (model_config_id) REFERENCES ai_model_config (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI Agent';

CREATE TABLE IF NOT EXISTS ai_prompt_template (
    id BIGINT NOT NULL COMMENT '主键',
    create_by BIGINT NOT NULL DEFAULT 0 COMMENT '创建人用户 ID',
    update_by BIGINT NOT NULL DEFAULT 0 COMMENT '更新人用户 ID',
    name VARCHAR(100) NOT NULL COMMENT '模板名称',
    code VARCHAR(50) NOT NULL COMMENT '模板唯一编码',
    type VARCHAR(20) NOT NULL DEFAULT 'user' COMMENT '类型：system、user、analysis',
    tags VARCHAR(200) DEFAULT NULL COMMENT '标签，逗号分隔',
    content TEXT NOT NULL COMMENT '提示词内容，支持 {{variable}} 占位符',
    variables JSON COMMENT '变量定义 JSON',
    description VARCHAR(500) DEFAULT NULL COMMENT '模板描述',
    example_input TEXT COMMENT '示例输入',
    example_output TEXT COMMENT '示例输出',
    public_template TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否公开',
    enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
    sequence INT NOT NULL DEFAULT 0 COMMENT '排序号',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_prompt_template_code (code),
    KEY idx_ai_prompt_template_type (type),
    KEY idx_ai_prompt_template_tags (tags),
    KEY idx_ai_prompt_template_enabled (enabled, deleted, sequence)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI 提示词模板';

CREATE TABLE IF NOT EXISTS ai_chat_session (
    id BIGINT NOT NULL COMMENT '主键',
    create_by BIGINT NOT NULL DEFAULT 0 COMMENT '创建人用户 ID',
    update_by BIGINT NOT NULL DEFAULT 0 COMMENT '更新人用户 ID',
    user_id BIGINT NOT NULL COMMENT '用户 ID',
    agent_code VARCHAR(50) NOT NULL COMMENT 'Agent 编码',
    business_type VARCHAR(50) DEFAULT NULL COMMENT '关联业务类型',
    business_id VARCHAR(128) DEFAULT NULL COMMENT '关联业务 ID',
    scene_code VARCHAR(64) NOT NULL COMMENT '复用会话的学习场景编码',
    title VARCHAR(200) DEFAULT NULL COMMENT '会话标题',
    variables_json JSON COMMENT '会话级变量 JSON',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    KEY idx_ai_chat_session_user_scene (user_id, scene_code, deleted, update_time),
    KEY idx_ai_chat_session_agent (agent_code),
    KEY idx_ai_chat_session_biz (business_type, business_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI 对话会话';

CREATE TABLE IF NOT EXISTS ai_chat_message (
    id BIGINT NOT NULL COMMENT '主键',
    create_by BIGINT NOT NULL DEFAULT 0 COMMENT '创建人用户 ID',
    update_by BIGINT NOT NULL DEFAULT 0 COMMENT '更新人用户 ID',
    session_id BIGINT NOT NULL COMMENT '会话 ID',
    role VARCHAR(20) NOT NULL COMMENT '角色：system、user、assistant',
    content MEDIUMTEXT NOT NULL COMMENT '消息内容',
    token_count INT DEFAULT NULL COMMENT 'Token 数量',
    cost_time BIGINT DEFAULT NULL COMMENT '耗时，单位毫秒',
    model_provider VARCHAR(50) DEFAULT NULL COMMENT '模型供应商',
    model_name VARCHAR(100) DEFAULT NULL COMMENT '模型名称',
    sequence INT NOT NULL DEFAULT 0 COMMENT '会话内消息序号',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_chat_message_session_sequence (session_id, sequence),
    CONSTRAINT fk_ai_chat_message_session FOREIGN KEY (session_id) REFERENCES ai_chat_session (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI 对话消息';

CREATE TABLE IF NOT EXISTS ai_model_call_record (
    id BIGINT NOT NULL COMMENT '主键',
    create_by BIGINT NOT NULL DEFAULT 0 COMMENT '创建人用户 ID',
    update_by BIGINT NOT NULL DEFAULT 0 COMMENT '更新人用户 ID',
    session_id BIGINT DEFAULT NULL COMMENT '会话 ID',
    agent_code VARCHAR(50) DEFAULT NULL COMMENT 'Agent 编码',
    invocation_scene_code VARCHAR(64) NOT NULL DEFAULT 'general_chat' COMMENT 'AI 调用场景编码',
    provider VARCHAR(50) NOT NULL COMMENT '模型供应商',
    model_name VARCHAR(100) NOT NULL COMMENT '模型名称',
    request_json JSON COMMENT '请求 JSON，不含认证信息',
    response_json MEDIUMTEXT COMMENT '原始响应 JSON',
    success TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否调用成功',
    error_message VARCHAR(2048) DEFAULT NULL COMMENT '失败信息',
    prompt_tokens INT DEFAULT NULL COMMENT '输入 Token 数',
    completion_tokens INT DEFAULT NULL COMMENT '输出 Token 数',
    total_tokens INT DEFAULT NULL COMMENT '总 Token 数',
    latency_ms BIGINT DEFAULT NULL COMMENT '耗时，单位毫秒',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    KEY idx_ai_model_call_session (session_id),
    KEY idx_ai_model_call_agent (agent_code),
    KEY idx_ai_model_call_invocation_scene (invocation_scene_code, create_time),
    KEY idx_ai_model_call_provider (provider),
    KEY idx_ai_model_call_deleted_time (deleted, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI 模型调用记录';
