-- 用户、公共词卡缓存、个人单词本、复习与系统日志表。
-- 依赖 00_ai_schema_mysql.sql。

CREATE TABLE IF NOT EXISTS english_vocabulary_study_record (
    id BIGINT NOT NULL COMMENT '主键',
    create_by BIGINT NOT NULL DEFAULT 0 COMMENT '创建人用户 ID',
    update_by BIGINT NOT NULL DEFAULT 0 COMMENT '更新人用户 ID',
    term VARCHAR(128) NOT NULL COMMENT '标准展示单词或短语',
    normalized_term VARCHAR(128) NOT NULL COMMENT '归一化单词或短语',
    agent_code VARCHAR(50) NOT NULL COMMENT '生成词卡的 Agent 编码',
    template_code VARCHAR(50) NOT NULL COMMENT '生成词卡的模板编码',
    provider VARCHAR(50) DEFAULT NULL COMMENT '模型供应商',
    model_name VARCHAR(100) DEFAULT NULL COMMENT '模型名称',
    session_id BIGINT DEFAULT NULL COMMENT 'AI 对话会话 ID',
    raw_content MEDIUMTEXT NOT NULL COMMENT 'AI 原始回复',
    parsed_json JSON COMMENT '结构化词卡 JSON',
    token_usage INT DEFAULT NULL COMMENT 'Token 用量',
    cost_time BIGINT DEFAULT NULL COMMENT '耗时，单位毫秒',
    lookup_count INT NOT NULL DEFAULT 1 COMMENT '缓存查询次数',
    last_lookup_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最近查询时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_english_vocabulary_normalized_term (normalized_term),
    KEY idx_english_vocabulary_agent (agent_code),
    KEY idx_english_vocabulary_session (session_id),
    KEY idx_english_vocabulary_update_time (deleted, update_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='公共英语词汇学习卡缓存';

CREATE TABLE IF NOT EXISTS learning_user (
    id BIGINT NOT NULL COMMENT '主键',
    create_by BIGINT NOT NULL DEFAULT 0 COMMENT '创建人用户 ID',
    update_by BIGINT NOT NULL DEFAULT 0 COMMENT '更新人用户 ID',
    username VARCHAR(64) NOT NULL COMMENT '登录用户名',
    nickname VARCHAR(64) DEFAULT NULL COMMENT '昵称',
    phone VARCHAR(32) DEFAULT NULL COMMENT '手机号码',
    email VARCHAR(128) DEFAULT NULL COMMENT '联系邮箱',
    password_hash VARCHAR(128) NOT NULL COMMENT '密码哈希',
    enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
    last_login_time DATETIME DEFAULT NULL COMMENT '最近登录时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_learning_user_username (username),
    KEY idx_learning_user_update_time (deleted, update_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='学习助手用户';

CREATE TABLE IF NOT EXISTS learning_user_token (
    id BIGINT NOT NULL COMMENT '主键',
    create_by BIGINT NOT NULL DEFAULT 0 COMMENT '创建人用户 ID',
    update_by BIGINT NOT NULL DEFAULT 0 COMMENT '更新人用户 ID',
    user_id BIGINT NOT NULL COMMENT '用户 ID',
    token_hash VARCHAR(128) NOT NULL COMMENT '访问令牌 SHA-256 哈希',
    expired_time DATETIME NOT NULL COMMENT '过期时间',
    revoked TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已注销',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_learning_user_token_hash (token_hash),
    KEY idx_learning_user_token_user (user_id, deleted),
    KEY idx_learning_user_token_expired_time (expired_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='学习助手登录令牌';

CREATE TABLE IF NOT EXISTS learning_wordbook (
    id BIGINT NOT NULL COMMENT '主键',
    create_by BIGINT NOT NULL DEFAULT 0 COMMENT '创建人用户 ID',
    update_by BIGINT NOT NULL DEFAULT 0 COMMENT '更新人用户 ID',
    user_id BIGINT NOT NULL COMMENT '用户 ID',
    name VARCHAR(64) NOT NULL COMMENT '单词本名称',
    description VARCHAR(255) DEFAULT NULL COMMENT '单词本描述',
    is_default TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否默认单词本',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    KEY idx_learning_wordbook_user (user_id, deleted, update_time),
    KEY idx_learning_wordbook_default (user_id, is_default, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='个人学习单词本';

CREATE TABLE IF NOT EXISTS learning_wordbook_entry (
    id BIGINT NOT NULL COMMENT '主键',
    create_by BIGINT NOT NULL DEFAULT 0 COMMENT '创建人用户 ID',
    update_by BIGINT NOT NULL DEFAULT 0 COMMENT '更新人用户 ID',
    user_id BIGINT NOT NULL COMMENT '词条所属用户 ID',
    wordbook_id BIGINT NOT NULL COMMENT '个人单词本 ID',
    progress_id BIGINT DEFAULT NULL COMMENT '用户跨词本逐词进度 ID',
    catalog_entry_id BIGINT DEFAULT NULL COMMENT '来源公共词表词条 ID',
    vocabulary_id BIGINT DEFAULT NULL COMMENT '公共词卡缓存 ID，词卡生成前可为空',
    term VARCHAR(128) NOT NULL COMMENT '展示单词或短语',
    normalized_term VARCHAR(128) NOT NULL COMMENT '归一化单词或短语',
    note TEXT DEFAULT NULL COMMENT '用户 Markdown 笔记',
    snapshot_raw_content MEDIUMTEXT DEFAULT NULL COMMENT '加入单词本时的 AI 原始回复快照',
    snapshot_parsed_json JSON DEFAULT NULL COMMENT '加入单词本时的结构化词卡快照',
    snapshot_tags_json JSON DEFAULT NULL COMMENT '加入单词本时的标签快照',
    snapshot_relations_json JSON DEFAULT NULL COMMENT '加入单词本时的关联词快照',
    snapshot_provider VARCHAR(50) DEFAULT NULL COMMENT '快照模型供应商',
    snapshot_model_name VARCHAR(100) DEFAULT NULL COMMENT '快照模型名称',
    snapshot_session_id BIGINT DEFAULT NULL COMMENT '快照关联 AI 会话 ID',
    snapshot_time DATETIME DEFAULT NULL COMMENT '快照生成时间',
    card_status VARCHAR(20) NOT NULL DEFAULT 'missing' COMMENT '词卡状态：missing、queued、generating、ready、failed、not_required',
    card_error_message VARCHAR(1000) DEFAULT NULL COMMENT '词卡生成失败原因',
    card_generated_time DATETIME DEFAULT NULL COMMENT '词卡生成完成时间',
    status VARCHAR(20) NOT NULL DEFAULT 'vague' COMMENT '熟练状态：familiar、forgotten、vague',
    review_stage INT NOT NULL DEFAULT 0 COMMENT '艾宾浩斯复习阶段',
    mastery_score INT NOT NULL DEFAULT 0 COMMENT '掌握度 0-100',
    first_review_time DATETIME DEFAULT NULL COMMENT '首次复习时间',
    last_review_time DATETIME DEFAULT NULL COMMENT '最近复习时间',
    next_review_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '下次复习时间',
    due_count INT NOT NULL DEFAULT 0 COMMENT '进入复习队列次数',
    review_count INT NOT NULL DEFAULT 0 COMMENT '复习次数',
    correct_count INT NOT NULL DEFAULT 0 COMMENT '记住次数',
    wrong_count INT NOT NULL DEFAULT 0 COMMENT '忘记次数',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_learning_wordbook_entry_term (wordbook_id, normalized_term),
    KEY idx_learning_wordbook_entry_user_due (user_id, deleted, next_review_time),
    KEY idx_learning_wordbook_entry_vocabulary (vocabulary_id),
    KEY idx_learning_wordbook_entry_status (wordbook_id, status, deleted),
    KEY idx_learning_wordbook_entry_progress (progress_id, deleted),
    KEY idx_learning_wordbook_entry_catalog (catalog_entry_id, deleted),
    KEY idx_learning_wordbook_entry_wb_due_order (user_id, wordbook_id, deleted, next_review_time, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='个人单词本词条与复习状态';

CREATE TABLE IF NOT EXISTS learning_vocabulary_tag (
    id BIGINT NOT NULL COMMENT '主键',
    create_by BIGINT NOT NULL DEFAULT 0 COMMENT '创建人用户 ID',
    update_by BIGINT NOT NULL DEFAULT 0 COMMENT '更新人用户 ID',
    vocabulary_id BIGINT NOT NULL COMMENT '公共词卡缓存 ID',
    normalized_term VARCHAR(128) NOT NULL COMMENT '归一化单词或短语',
    tag_type VARCHAR(50) NOT NULL COMMENT '标签类型',
    tag_value VARCHAR(128) NOT NULL COMMENT '标签值',
    display_name VARCHAR(128) NOT NULL COMMENT '展示名称',
    weight INT NOT NULL DEFAULT 50 COMMENT '标签权重 0-100',
    source VARCHAR(50) NOT NULL DEFAULT 'parsed_json' COMMENT '标签来源',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_learning_vocabulary_tag (vocabulary_id, tag_type, tag_value),
    KEY idx_learning_vocabulary_tag_lookup (normalized_term, tag_type, deleted),
    KEY idx_learning_vocabulary_tag_value (tag_type, tag_value)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='词汇多维标签';

CREATE TABLE IF NOT EXISTS learning_vocabulary_relation (
    id BIGINT NOT NULL COMMENT '主键',
    create_by BIGINT NOT NULL DEFAULT 0 COMMENT '创建人用户 ID',
    update_by BIGINT NOT NULL DEFAULT 0 COMMENT '更新人用户 ID',
    vocabulary_id BIGINT NOT NULL COMMENT '当前公共词卡缓存 ID',
    related_vocabulary_id BIGINT DEFAULT NULL COMMENT '已入库关联词卡缓存 ID',
    normalized_term VARCHAR(128) NOT NULL COMMENT '当前词归一化值',
    related_term VARCHAR(128) NOT NULL COMMENT '关联词',
    relation_type VARCHAR(50) NOT NULL COMMENT '语义关系：synonym、antonym、word_family',
    relation_value VARCHAR(128) DEFAULT NULL COMMENT '关系说明',
    related_part_of_speech VARCHAR(50) DEFAULT NULL COMMENT '关联词词性',
    related_meaning VARCHAR(512) DEFAULT NULL COMMENT '关联词核心含义',
    match_type VARCHAR(50) DEFAULT NULL COMMENT '匹配来源',
    match_score INT DEFAULT NULL COMMENT '匹配分数 0-100',
    score INT NOT NULL DEFAULT 50 COMMENT '相关度 0-100',
    source VARCHAR(50) NOT NULL DEFAULT 'parsed_json' COMMENT '关系来源',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_learning_vocabulary_relation (normalized_term, related_term, relation_type),
    KEY idx_learning_vocabulary_relation_term (normalized_term, score, deleted),
    KEY idx_learning_vocabulary_relation_related (related_term),
    KEY idx_learning_vocabulary_relation_match (normalized_term, match_type, match_score)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='词汇语义关联关系';

CREATE TABLE IF NOT EXISTS learning_vocabulary_alias (
    id BIGINT NOT NULL COMMENT '主键',
    create_by BIGINT NOT NULL DEFAULT 0 COMMENT '创建人用户 ID',
    update_by BIGINT NOT NULL DEFAULT 0 COMMENT '更新人用户 ID',
    vocabulary_id BIGINT NOT NULL COMMENT '公共词卡缓存 ID',
    alias_term VARCHAR(128) NOT NULL COMMENT '变形或别名单词',
    normalized_alias VARCHAR(128) NOT NULL COMMENT '归一化别名',
    lemma VARCHAR(128) NOT NULL COMMENT '原形单词',
    normalized_lemma VARCHAR(128) NOT NULL COMMENT '归一化原形',
    alias_type VARCHAR(50) NOT NULL COMMENT '别名类型：exact, plural, past_tense, past_participle, present_participle, third_person_singular, comparative, superlative, irregular, ai_generated',
    source VARCHAR(50) NOT NULL DEFAULT 'rule' COMMENT '来源：rule, ai, manual',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_learning_vocabulary_alias (normalized_alias, vocabulary_id),
    KEY idx_learning_vocabulary_alias_lookup (normalized_alias, deleted),
    KEY idx_learning_vocabulary_alias_vocab (vocabulary_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='英语词汇形态变形与别名索引';

CREATE TABLE IF NOT EXISTS learning_review_record (
    id BIGINT NOT NULL COMMENT '主键',
    create_by BIGINT NOT NULL DEFAULT 0 COMMENT '创建人用户 ID',
    update_by BIGINT NOT NULL DEFAULT 0 COMMENT '更新人用户 ID',
    user_id BIGINT NOT NULL COMMENT '用户 ID',
    wordbook_id BIGINT NOT NULL COMMENT '个人单词本 ID',
    entry_id BIGINT NOT NULL COMMENT '个人单词本词条 ID',
    vocabulary_id BIGINT DEFAULT NULL COMMENT '公共词卡缓存 ID，词卡生成前可为空',
    word_progress_id BIGINT DEFAULT NULL COMMENT '用户逐词进度 ID',
    plan_id BIGINT DEFAULT NULL COMMENT '场景学习计划 ID',
    unit_id BIGINT DEFAULT NULL COMMENT '场景学习单元 ID',
    assessment_type VARCHAR(30) DEFAULT NULL COMMENT '检查类型：meaning_choice、copy_typing、meaning_spelling',
    question_json JSON DEFAULT NULL COMMENT '题目与选项快照',
    answer_text VARCHAR(1000) DEFAULT NULL COMMENT '学习者答案',
    correct_answer VARCHAR(1000) DEFAULT NULL COMMENT '正确答案快照',
    check_result VARCHAR(20) DEFAULT NULL COMMENT '系统判定：correct、incorrect',
    typing_accuracy DECIMAL(5,2) DEFAULT NULL COMMENT '拼写准确率 0-100',
    hint_level INT DEFAULT NULL COMMENT '使用提示级别',
    attempt_count INT DEFAULT NULL COMMENT '本题尝试次数',
    duration_millis BIGINT DEFAULT NULL COMMENT '本次检查耗时毫秒',
    normalized_term VARCHAR(128) NOT NULL COMMENT '归一化单词或短语',
    result VARCHAR(20) NOT NULL COMMENT '复习结果：remembered、vague、forgotten',
    score INT DEFAULT NULL COMMENT '本次自评分',
    review_stage_before INT NOT NULL COMMENT '复习前阶段',
    review_stage_after INT NOT NULL COMMENT '复习后阶段',
    mastery_before INT NOT NULL COMMENT '复习前掌握度',
    mastery_after INT NOT NULL COMMENT '复习后掌握度',
    next_review_time DATETIME NOT NULL COMMENT '下次复习时间',
    duration_seconds INT DEFAULT NULL COMMENT '本次复习耗时秒数',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    KEY idx_learning_review_record_user_deleted_time (user_id, deleted, create_time),
    KEY idx_learning_review_record_entry (entry_id, create_time),
    KEY idx_learning_review_record_term (normalized_term),
    KEY idx_learning_review_record_progress_type (word_progress_id, assessment_type, create_time),
    KEY idx_learning_review_record_unit_entry (unit_id, entry_id, check_result, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='逐词学习与复习检查记录';

CREATE TABLE IF NOT EXISTS learning_user_preference (
    id BIGINT NOT NULL COMMENT '主键',
    create_by BIGINT NOT NULL DEFAULT 0 COMMENT '创建人用户 ID',
    update_by BIGINT NOT NULL DEFAULT 0 COMMENT '更新人用户 ID',
    user_id BIGINT NOT NULL COMMENT '用户 ID',
    preference_key VARCHAR(80) NOT NULL COMMENT '偏好键，例如 speech.voice_type',
    preference_value TEXT DEFAULT NULL COMMENT '偏好值',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_learning_user_preference (user_id, preference_key),
    KEY idx_learning_user_preference_user (user_id, deleted, update_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户偏好设置';

CREATE TABLE IF NOT EXISTS learning_system_log (
    id BIGINT NOT NULL COMMENT '主键',
    create_by BIGINT NOT NULL DEFAULT 0 COMMENT '创建人用户 ID',
    update_by BIGINT NOT NULL DEFAULT 0 COMMENT '更新人用户 ID',
    user_id BIGINT NOT NULL COMMENT '用户 ID',
    log_type VARCHAR(64) NOT NULL COMMENT '日志类型：auth、ai、cache、review、wordbook、error 等',
    title VARCHAR(180) NOT NULL COMMENT '业务可读日志标题',
    detail TEXT COMMENT '日志详情',
    source VARCHAR(32) NOT NULL DEFAULT 'server' COMMENT '来源：server、client',
    business_type VARCHAR(64) DEFAULT NULL COMMENT '关联业务类型',
    business_id VARCHAR(128) DEFAULT NULL COMMENT '关联业务 ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    KEY idx_learning_system_log_user_deleted_time (user_id, deleted, create_time),
    KEY idx_learning_system_log_type_time (log_type, create_time),
    KEY idx_learning_system_log_business (business_type, business_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='学习助手系统日志';

CREATE TABLE IF NOT EXISTS learning_system_log_outbox (
    id BIGINT NOT NULL COMMENT '事件主键，同时作为最终系统日志主键',
    create_by BIGINT NOT NULL DEFAULT 0 COMMENT '创建人用户 ID',
    update_by BIGINT NOT NULL DEFAULT 0 COMMENT '更新人用户 ID',
    user_id BIGINT NOT NULL COMMENT '日志归属用户 ID',
    log_type VARCHAR(64) NOT NULL COMMENT '日志类型',
    title VARCHAR(180) NOT NULL COMMENT '业务可读日志标题',
    detail TEXT COMMENT '有长度边界的日志详情',
    source VARCHAR(32) NOT NULL COMMENT '来源：server、client',
    business_type VARCHAR(64) DEFAULT NULL COMMENT '关联业务类型',
    business_id VARCHAR(128) DEFAULT NULL COMMENT '关联业务 ID',
    occurred_at DATETIME NOT NULL COMMENT '业务动作发生时间',
    trace_id VARCHAR(64) DEFAULT NULL COMMENT '请求链路标识',
    status VARCHAR(20) NOT NULL DEFAULT 'pending' COMMENT '投递状态：pending、processing、succeeded',
    claim_token VARCHAR(64) DEFAULT NULL COMMENT '异步投递领取令牌',
    processed_time DATETIME DEFAULT NULL COMMENT '成功写入最终系统日志表时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    KEY idx_learning_system_log_outbox_status (status, deleted, create_time),
    KEY idx_learning_system_log_outbox_claim (claim_token, status, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统日志可靠异步投递事件';
