-- 语境精读文章记录表。
-- 依赖 20_vocabulary_plan_schema_mysql.sql。

CREATE TABLE IF NOT EXISTS learning_article_study_record (
    id BIGINT NOT NULL COMMENT '主键',
    create_by BIGINT NOT NULL DEFAULT 0 COMMENT '创建人用户 ID',
    update_by BIGINT NOT NULL DEFAULT 0 COMMENT '更新人用户 ID',
    user_id BIGINT NOT NULL COMMENT '用户 ID',
    wordbook_id BIGINT NOT NULL COMMENT '个人单词本 ID',
    plan_id BIGINT DEFAULT NULL COMMENT '来源场景学习计划 ID',
    plan_unit_id BIGINT DEFAULT NULL COMMENT '来源场景学习单元 ID',
    selected_terms_json JSON NOT NULL COMMENT '生成材料时选择的目标词摘要 JSON',
    selected_term_hash VARCHAR(128) NOT NULL COMMENT '用户、词本、目标词和参数生成的缓存哈希',
    word_count_range VARCHAR(20) NOT NULL COMMENT '文章字数范围：150-200、300-500、500-700、800-1000',
    difficulty VARCHAR(20) NOT NULL COMMENT '文章难度：easy、medium、hard',
    remark VARCHAR(1000) DEFAULT NULL COMMENT '文章主题或学习要求',
    agent_code VARCHAR(50) NOT NULL COMMENT '调用的 Agent 编码',
    template_code VARCHAR(50) NOT NULL COMMENT '调用的提示词模板编码',
    provider VARCHAR(50) DEFAULT NULL COMMENT '模型供应商',
    model_name VARCHAR(100) DEFAULT NULL COMMENT '模型名称',
    session_id BIGINT DEFAULT NULL COMMENT '复用的 AI 会话 ID',
    raw_content MEDIUMTEXT DEFAULT NULL COMMENT 'AI 原始回复',
    parsed_json JSON DEFAULT NULL COMMENT '结构化语境精读 JSON',
    token_usage INT DEFAULT NULL COMMENT 'Token 使用量',
    cost_time BIGINT DEFAULT NULL COMMENT '模型调用耗时毫秒',
    lookup_count INT NOT NULL DEFAULT 1 COMMENT '读取次数',
    last_lookup_time DATETIME DEFAULT NULL COMMENT '最近读取时间',
    study_status VARCHAR(20) NOT NULL DEFAULT 'generated' COMMENT '精读状态：generated、in_progress、completed',
    current_stage VARCHAR(20) NOT NULL DEFAULT 'reading' COMMENT '当前阶段：reading、vocabulary、check、completed',
    practice_total INT NOT NULL DEFAULT 0 COMMENT '阅读检测题总数',
    practice_correct INT NOT NULL DEFAULT 0 COMMENT '阅读检测答对数',
    practice_score INT NOT NULL DEFAULT 0 COMMENT '阅读检测得分 0-100',
    started_time DATETIME DEFAULT NULL COMMENT '开始精读时间',
    completed_time DATETIME DEFAULT NULL COMMENT '完成精读时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    KEY idx_learning_article_user_wordbook_hash (user_id, wordbook_id, selected_term_hash, deleted),
    KEY idx_learning_article_user_status (user_id, study_status, deleted, update_time),
    KEY idx_learning_article_user_time (user_id, deleted, update_time),
    KEY idx_learning_article_wordbook_time (wordbook_id, deleted, update_time),
    KEY idx_learning_article_plan_unit (plan_id, plan_unit_id, deleted),
    KEY idx_learning_article_session (session_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='语境精读文章学习记录';
