-- FCC initial schema
-- Forward-only additive migration. No business data backfill or destructive rollback.
-- Keep receipts if rolling back application code; archive closed/expired payloads under the privacy policy.
CREATE TABLE IF NOT EXISTS fcc_screen_pop_delivery (
 tenant_id BIGINT UNSIGNED NOT NULL,
 owner_work_no VARCHAR(64) NOT NULL,
 call_id BIGINT UNSIGNED NOT NULL,
 payload JSON NOT NULL,
 expires_at DATETIME(3) NOT NULL,
 received_at DATETIME(3) NULL,
 shown_at DATETIME(3) NULL,
 activated_at DATETIME(3) NULL,
 unsupported_at DATETIME(3) NULL,
 closed_at DATETIME(3) NULL,
 PRIMARY KEY(tenant_id,owner_work_no,call_id),
 KEY idx_pop_owner_expiry(tenant_id,owner_work_no,closed_at,expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS fcc_event_inbox (
 event_id CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
 node_id VARCHAR(128) NOT NULL,
 payload JSON NOT NULL,
 status VARCHAR(16) NOT NULL,
 created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 KEY idx_inbox_status_time(status,updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS fcc_phone_binding_lock (
 tenant_id BIGINT UNSIGNED NOT NULL PRIMARY KEY
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS fcc_phone_binding_challenge (
 tenant_id BIGINT UNSIGNED NOT NULL,
 owner_work_no VARCHAR(64) NOT NULL,
 extension VARCHAR(32) NOT NULL,
 code_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 status VARCHAR(16) NOT NULL,
 expires_at DATETIME(3) NOT NULL,
 channel_uuid VARCHAR(64) NULL,
 updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 PRIMARY KEY(tenant_id,owner_work_no),
 UNIQUE KEY uk_binding_code(code_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Customer schema is mirrored in docs/migrations/20260920_customer.sql for existing databases.
CREATE TABLE IF NOT EXISTS fcc_customer (
 id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
 tenant_id BIGINT UNSIGNED NOT NULL,
 owner_work_no VARCHAR(64) NOT NULL,
 name VARCHAR(128) NOT NULL,
 phone_number VARCHAR(32) NOT NULL,
 company_name VARCHAR(255) NULL,
 notes TEXT NULL,
 version BIGINT UNSIGNED NOT NULL DEFAULT 0,
 created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 KEY idx_customer_owner_page(tenant_id,owner_work_no,id),
 KEY idx_customer_owner_phone(tenant_id,owner_work_no,phone_number,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Database: MySQL 8.0+
-- Time policy: application writes UTC; datetime precision is milliseconds.
-- ID policy: BIGINT IDs are generated by the application (Snowflake/segment).
-- Foreign keys are intentionally logical to support high-volume writes, partitioning
-- and online archiving. Unique keys and application transactions enforce integrity.

SET NAMES utf8mb4;
SET time_zone = '+00:00';

-- -----------------------------------------------------------------------------
-- Telephony resources
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS fcc_telephony_node (
    id                  BIGINT UNSIGNED NOT NULL,
    tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    node_id             VARCHAR(128) NOT NULL,
    cluster_id          VARCHAR(64) NOT NULL DEFAULT 'default',
    host                VARCHAR(255) NULL,
    zone                VARCHAR(64) NULL,
    status              VARCHAR(32) NOT NULL DEFAULT 'OFFLINE',
    max_channels        INT UNSIGNED NOT NULL DEFAULT 0,
    active_channels     INT UNSIGNED NOT NULL DEFAULT 0,
    draining_since      DATETIME(3) NULL,
    last_heartbeat_at   DATETIME(3) NULL,
    metadata            JSON NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_node_tenant_node (tenant_id, node_id),
    KEY idx_node_status_heartbeat (status, last_heartbeat_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='FreeSWITCH/Sidecar node registry';

CREATE TABLE IF NOT EXISTS fcc_telephony_trunk (
    id                  BIGINT UNSIGNED NOT NULL,
    tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    trunk_code          VARCHAR(64) NOT NULL,
    trunk_name          VARCHAR(128) NOT NULL,
    carrier_code        VARCHAR(64) NULL,
    gateway_name        VARCHAR(128) NOT NULL,
    direction           VARCHAR(16) NOT NULL DEFAULT 'BOTH',
    status              VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    max_concurrent      INT UNSIGNED NOT NULL DEFAULT 0,
    config_json         JSON NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at          DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_trunk_tenant_code (tenant_id, trunk_code),
    KEY idx_trunk_gateway (tenant_id, gateway_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='SIP trunk and carrier gateway';

CREATE TABLE IF NOT EXISTS fcc_did_number (
    id                  BIGINT UNSIGNED NOT NULL,
    tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    trunk_id            BIGINT UNSIGNED NULL,
    phone_number        VARCHAR(32) NOT NULL,
    route_key           VARCHAR(128) NULL,
    status              VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at          DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_did_tenant_number (tenant_id, phone_number),
    KEY idx_did_trunk (trunk_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Inbound DID number';

CREATE TABLE IF NOT EXISTS fcc_outbound_number (
    id                  BIGINT UNSIGNED NOT NULL,
    tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    trunk_id            BIGINT UNSIGNED NOT NULL,
    phone_number        VARCHAR(32) NOT NULL,
    pool_code           VARCHAR(64) NOT NULL DEFAULT 'default',
    status              VARCHAR(32) NOT NULL DEFAULT 'AVAILABLE',
    max_concurrent      INT UNSIGNED NOT NULL DEFAULT 1,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at          DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_outbound_tenant_number (tenant_id, phone_number),
    KEY idx_outbound_pool_status (tenant_id, pool_code, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Outbound caller number pool';

CREATE TABLE IF NOT EXISTS fcc_extension (
    id                  BIGINT UNSIGNED NOT NULL,
    tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    extension           VARCHAR(32) NOT NULL,
    endpoint_type       VARCHAR(32) NOT NULL DEFAULT 'SIP',
    credential_secret   VARBINARY(512) NULL,
    status              VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    agent_work_no       VARCHAR(64) NULL COMMENT '当前绑定的坐席工号',
    agent_name          VARCHAR(128) NULL COMMENT '当前绑定的坐席姓名',
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at          DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_extension_tenant_number (tenant_id, extension),
    KEY idx_ext_agent_work_no (tenant_id, agent_work_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='SIP/WebRTC extension';

CREATE TABLE IF NOT EXISTS fcc_endpoint_registration_event (
    id                  BIGINT UNSIGNED NOT NULL,
    tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    extension_id        BIGINT UNSIGNED NULL,
    extension           VARCHAR(32) NOT NULL,
    protocol            VARCHAR(16) NOT NULL,
    status              VARCHAR(32) NOT NULL,
    contact             VARCHAR(512) NULL,
    user_agent          VARCHAR(512) NULL,
    network_ip          VARCHAR(64) NULL,
    network_port        INT UNSIGNED NULL,
    node_id             VARCHAR(128) NULL,
    occurred_at         DATETIME(3) NOT NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_registration_extension_time (tenant_id, extension, occurred_at),
    KEY idx_registration_node_time (node_id, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Append-only endpoint registration history';

-- -----------------------------------------------------------------------------
-- Agent domain
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS fcc_agent (
    id                    BIGINT UNSIGNED NOT NULL,
    tenant_id             BIGINT UNSIGNED NOT NULL DEFAULT 0,
    work_no               VARCHAR(64) NOT NULL,
    agent_name            VARCHAR(128) NOT NULL,
    phone_number          VARCHAR(32) NULL,
    role_code             VARCHAR(64) NULL,
    status                VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    password_hash         VARCHAR(255) NULL COMMENT '坐席登录口令派生串 pbkdf2-sha256$iterations$salt$hash，为空表示禁止登录',
    password_updated_at   DATETIME(3) NULL COMMENT '口令最近一次设置时间',
    last_login_at         DATETIME(3) NULL COMMENT '最近一次成功登录时间',
    current_extension     VARCHAR(32) NULL COMMENT '当前绑定使用的分机号',
    metadata              JSON NULL,
    created_at            DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at            DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at            DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_agent_tenant_work_no (tenant_id, work_no),
    KEY idx_agent_phone (tenant_id, phone_number),
    KEY idx_agent_cur_ext (tenant_id, current_extension)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Agent master data';

-- -----------------------------------------------------------------------------
-- Console accounts
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS fcc_admin_user (
    id                    BIGINT UNSIGNED NOT NULL,
    tenant_id             BIGINT UNSIGNED NOT NULL DEFAULT 0,
    username              VARCHAR(64) NOT NULL COMMENT '管理控制台登录账号',
    real_name             VARCHAR(128) NOT NULL COMMENT '账号显示姓名',
    password_hash         VARCHAR(255) NOT NULL COMMENT '口令派生串 pbkdf2-sha256$iterations$salt$hash',
    password_updated_at   DATETIME(3) NULL COMMENT '口令最近一次设置时间',
    role_code             VARCHAR(64) NOT NULL DEFAULT 'ADMIN' COMMENT '控制台角色: ADMIN / OPERATOR / AUDITOR',
    status                VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT 'ENABLED / DISABLED',
    last_login_at         DATETIME(3) NULL COMMENT '最近一次成功登录时间',
    created_at            DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at            DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at            DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_admin_user_username (username),
    KEY idx_admin_user_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Management console account';

CREATE TABLE IF NOT EXISTS fcc_agent_group (
    id                  BIGINT UNSIGNED NOT NULL,
    tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    parent_id           BIGINT UNSIGNED NULL,
    group_code          VARCHAR(64) NOT NULL,
    group_name          VARCHAR(128) NOT NULL,
    group_type          VARCHAR(32) NOT NULL DEFAULT 'SKILL',
    routing_strategy    VARCHAR(32) NOT NULL DEFAULT 'LONGEST_IDLE',
    status              VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at          DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_group_tenant_code (tenant_id, group_code),
    KEY idx_group_parent (tenant_id, parent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Agent skill group';

CREATE TABLE IF NOT EXISTS fcc_agent_group_member (
    id                  BIGINT UNSIGNED NOT NULL,
    tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    group_id            BIGINT UNSIGNED NOT NULL,
    agent_id            BIGINT UNSIGNED NOT NULL,
    member_role         VARCHAR(32) NOT NULL DEFAULT 'MEMBER',
    priority            INT NOT NULL DEFAULT 0,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at          DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_group_member (tenant_id, group_id, agent_id),
    KEY idx_group_member_agent (tenant_id, agent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Agent and skill group membership';

CREATE TABLE IF NOT EXISTS fcc_agent_endpoint_binding (
    id                  BIGINT UNSIGNED NOT NULL,
    tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    agent_id            BIGINT UNSIGNED NOT NULL,
    endpoint_type       VARCHAR(32) NOT NULL,
    extension_id        BIGINT UNSIGNED NULL,
    endpoint_value      VARCHAR(128) NULL,
    priority            INT NOT NULL DEFAULT 0,
    status              VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    valid_from          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    valid_to            DATETIME(3) NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_binding_agent_status (tenant_id, agent_id, status),
    KEY idx_binding_extension (extension_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Agent endpoint binding history';

CREATE TABLE IF NOT EXISTS fcc_agent_presence (
    agent_id            BIGINT UNSIGNED NOT NULL,
    tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    login_status        VARCHAR(32) NOT NULL DEFAULT 'OFFLINE',
    work_status         VARCHAR(32) NOT NULL DEFAULT 'READY',
    answer_type         VARCHAR(32) NULL,
    active_call_id      BIGINT UNSIGNED NULL,
    login_at            DATETIME(3) NULL,
    last_state_at       DATETIME(3) NOT NULL,
    version             BIGINT UNSIGNED NOT NULL DEFAULT 0,
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (agent_id),
    KEY idx_presence_dispatch (tenant_id, login_status, work_status, last_state_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Current agent presence snapshot';

CREATE TABLE IF NOT EXISTS fcc_agent_state_interval (
    id                  BIGINT UNSIGNED NOT NULL,
    tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    agent_id            BIGINT UNSIGNED NOT NULL,
    state_type          VARCHAR(32) NOT NULL,
    state_value         VARCHAR(32) NOT NULL,
    started_at          DATETIME(3) NOT NULL,
    ended_at            DATETIME(3) NULL,
    duration_ms         BIGINT UNSIGNED NULL,
    source              VARCHAR(32) NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_agent_state_time (tenant_id, agent_id, started_at),
    KEY idx_agent_state_open (tenant_id, agent_id, ended_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Agent state interval facts';

-- -----------------------------------------------------------------------------
-- Call facts: Call -> Leg -> Bridge, Event and Command
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS fcc_call_session (
    id                  BIGINT UNSIGNED NOT NULL,
    tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    biz_id              VARCHAR(128) NULL,
    ctrl_id             VARCHAR(128) NOT NULL,
    model_type          VARCHAR(64) NOT NULL,
    flow_code           VARCHAR(64) NULL COMMENT '绑定的流程编码(如 FLOW-INBOUND)',
    route_mode          VARCHAR(32) NULL COMMENT '呼入路由模式(DID_DIRECT, RULE_ENGINE, HTTP_CALLBACK)',
    route_target_type   VARCHAR(32) NULL COMMENT '目标类型(AGENT, GROUP)',
    route_target_id     VARCHAR(64) NULL COMMENT '目标标识(工号/组ID)',
    direction           VARCHAR(16) NOT NULL,
    caller_number       VARCHAR(32) NULL,
    destination_number  VARCHAR(32) NULL,
    status              VARCHAR(32) NOT NULL,
    result              VARCHAR(32) NULL,
    started_at          DATETIME(3) NOT NULL,
    ringing_at          DATETIME(3) NULL,
    answered_at         DATETIME(3) NULL,
    ended_at            DATETIME(3) NULL,
    ring_duration_ms    BIGINT UNSIGNED NULL,
    talk_duration_ms    BIGINT UNSIGNED NULL,
    audio_duration_sec  INT UNSIGNED NULL DEFAULT 0 COMMENT '净通话时长(秒)',
    total_duration_ms   BIGINT UNSIGNED NULL,
    hangup_cause        VARCHAR(64) NULL,
    hangup_initiator    VARCHAR(32) NULL,
    primary_agent_id    BIGINT UNSIGNED NULL,
    primary_work_no     VARCHAR(64) NULL,
    agent_work_no       VARCHAR(64) NULL COMMENT '接听坐席工号',
    agent_name          VARCHAR(128) NULL COMMENT '接听坐席姓名',
    evaluation_score    SMALLINT UNSIGNED NULL,
    record_file_id      VARCHAR(128) NULL COMMENT '录音文件标识或路径',
    attributes          JSON NULL,
    version             BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_call_tenant_ctrl (tenant_id, ctrl_id),
    KEY idx_call_biz (tenant_id, biz_id),
    KEY idx_call_status_started (tenant_id, status, started_at),
    KEY idx_call_caller_started (tenant_id, caller_number, started_at),
    KEY idx_call_destination_started (tenant_id, destination_number, started_at),
    KEY idx_call_agent_started (tenant_id, primary_agent_id, started_at),
    KEY idx_call_eval_started (tenant_id, evaluation_score, started_at),
    KEY idx_cs_route_mode (tenant_id, route_mode),
    KEY idx_cs_agent_work_no (tenant_id, agent_work_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Business call aggregate';

CREATE TABLE IF NOT EXISTS fcc_call_leg (
    id                  BIGINT UNSIGNED NOT NULL,
    tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    call_id             BIGINT UNSIGNED NOT NULL,
    channel_uuid        VARCHAR(64) NOT NULL,
    node_id             VARCHAR(128) NOT NULL,
    parent_leg_id       BIGINT UNSIGNED NULL,
    role_type           VARCHAR(32) NOT NULL,
    direction           VARCHAR(16) NOT NULL,
    endpoint_type       VARCHAR(32) NULL,
    endpoint_id         VARCHAR(128) NULL,
    caller_number       VARCHAR(32) NULL,
    destination_number  VARCHAR(32) NULL,
    trunk_id            BIGINT UNSIGNED NULL,
    gateway_name        VARCHAR(128) NULL,
    state               VARCHAR(32) NOT NULL,
    attempt_no          INT UNSIGNED NOT NULL DEFAULT 1,
    created_time        DATETIME(3) NOT NULL,
    ringing_at          DATETIME(3) NULL,
    answered_at         DATETIME(3) NULL,
    bridged_at          DATETIME(3) NULL,
    ended_at            DATETIME(3) NULL,
    ring_duration_ms    BIGINT UNSIGNED NULL,
    talk_duration_ms    BIGINT UNSIGNED NULL,
    hangup_cause        VARCHAR(64) NULL,
    sip_status          INT UNSIGNED NULL,
    metadata            JSON NULL,
    version             BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_leg_channel_uuid (channel_uuid),
    KEY idx_leg_call_role (tenant_id, call_id, role_type),
    KEY idx_leg_node_state (node_id, state),
    KEY idx_leg_parent (parent_leg_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='FreeSWITCH channel/leg fact';

CREATE TABLE IF NOT EXISTS fcc_call_bridge (
    id                  BIGINT UNSIGNED NOT NULL,
    tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    call_id             BIGINT UNSIGNED NOT NULL,
    bridge_uuid         VARCHAR(64) NOT NULL,
    bridge_type         VARCHAR(32) NOT NULL DEFAULT 'DIRECT',
    started_at          DATETIME(3) NOT NULL,
    ended_at            DATETIME(3) NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_bridge_uuid (bridge_uuid),
    KEY idx_bridge_call_time (tenant_id, call_id, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Time-scoped media bridge';

CREATE TABLE IF NOT EXISTS fcc_call_bridge_member (
    id                  BIGINT UNSIGNED NOT NULL,
    bridge_id           BIGINT UNSIGNED NOT NULL,
    leg_id              BIGINT UNSIGNED NOT NULL,
    joined_at           DATETIME(3) NOT NULL,
    left_at             DATETIME(3) NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_bridge_member_join (bridge_id, leg_id, joined_at),
    KEY idx_bridge_member_leg (leg_id, joined_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Bridge leg membership';

CREATE TABLE IF NOT EXISTS fcc_call_event (
    id                  BIGINT UNSIGNED NOT NULL,
    tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    event_id            VARCHAR(128) NOT NULL,
    node_id             VARCHAR(128) NOT NULL,
    call_id             BIGINT UNSIGNED NULL,
    leg_id              BIGINT UNSIGNED NULL,
    channel_uuid        VARCHAR(64) NULL,
    event_type          VARCHAR(64) NOT NULL,
    event_sequence      BIGINT UNSIGNED NULL,
    event_time          DATETIME(3) NOT NULL,
    received_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    normalized_payload  JSON NULL,
    raw_payload         JSON NULL,
    process_status      VARCHAR(32) NOT NULL DEFAULT 'RECEIVED',
    process_error       VARCHAR(1024) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_event_id (event_id),
    KEY idx_event_call_time (tenant_id, call_id, event_time),
    KEY idx_event_leg_time (leg_id, event_time),
    KEY idx_event_channel_time (channel_uuid, event_time),
    KEY idx_event_process (process_status, received_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Append-only normalized and raw telephony event';

CREATE TABLE IF NOT EXISTS fcc_call_command (
    id                  BIGINT UNSIGNED NOT NULL,
    tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    command_id          VARCHAR(128) NOT NULL,
    idempotency_key     VARCHAR(128) NOT NULL,
    call_id             BIGINT UNSIGNED NULL,
    leg_id              BIGINT UNSIGNED NULL,
    target_node_id      VARCHAR(128) NOT NULL,
    method_name         VARCHAR(64) NOT NULL,
    request_payload     JSON NULL,
    response_payload    JSON NULL,
    status              VARCHAR(32) NOT NULL DEFAULT 'CREATED',
    error_code          VARCHAR(64) NULL,
    error_message       VARCHAR(1024) NULL,
    retry_count         INT UNSIGNED NOT NULL DEFAULT 0,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    sent_at             DATETIME(3) NULL,
    completed_at        DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_command_id (command_id),
    UNIQUE KEY uk_command_idempotency (tenant_id, idempotency_key),
    KEY idx_command_call_created (tenant_id, call_id, created_at),
    KEY idx_command_status_created (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='FCC FNode command audit and idempotency';

CREATE TABLE IF NOT EXISTS fcc_call_recording (
    id                  BIGINT UNSIGNED NOT NULL,
    tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    recording_id        VARCHAR(128) NOT NULL,
    call_id             BIGINT UNSIGNED NOT NULL,
    leg_id              BIGINT UNSIGNED NULL,
    bridge_id           BIGINT UNSIGNED NULL,
    node_id             VARCHAR(128) NULL COMMENT '写出该录音文件的 Sidecar/FreeSWITCH 节点',
    status              VARCHAR(32) NOT NULL,
    storage_type        VARCHAR(32) NOT NULL DEFAULT 'OBJECT_STORAGE',
    bucket_name         VARCHAR(128) NULL,
    object_key          VARCHAR(512) NOT NULL COMMENT '录音文件地址: 共享存储绝对路径，或远端对象存储 URL',
    media_format        VARCHAR(32) NULL,
    size_bytes          BIGINT UNSIGNED NULL,
    duration_ms         BIGINT UNSIGNED NULL,
    checksum            VARCHAR(128) NULL,
    started_at          DATETIME(3) NULL,
    completed_at        DATETIME(3) NULL,
    retain_until        DATETIME(3) NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_recording_id (recording_id),
    KEY idx_recording_call (tenant_id, call_id),
    KEY idx_recording_retain (retain_until)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Call recording metadata';

-- -----------------------------------------------------------------------------
-- Flow and routing
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS fcc_flow_definition (
    id                  BIGINT UNSIGNED NOT NULL,
    tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    flow_key            VARCHAR(128) NOT NULL,
    flow_name           VARCHAR(128) NOT NULL,
    model_type          VARCHAR(64) NOT NULL,
    status              VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    current_version     INT UNSIGNED NOT NULL DEFAULT 0,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at          DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_flow_tenant_key (tenant_id, flow_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Flow definition identity';

CREATE TABLE IF NOT EXISTS fcc_flow_definition_version (
    id                  BIGINT UNSIGNED NOT NULL,
    flow_definition_id  BIGINT UNSIGNED NOT NULL,
    version_no          INT UNSIGNED NOT NULL,
    definition_json     JSON NOT NULL,
    checksum            VARCHAR(128) NOT NULL,
    publish_status      VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    published_at        DATETIME(3) NULL,
    created_by          VARCHAR(128) NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_flow_version (flow_definition_id, version_no),
    KEY idx_flow_version_publish (flow_definition_id, publish_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Immutable flow definition version';

CREATE TABLE IF NOT EXISTS fcc_flow_instance (
    id                  BIGINT UNSIGNED NOT NULL,
    tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    call_id             BIGINT UNSIGNED NOT NULL,
    flow_definition_id  BIGINT UNSIGNED NOT NULL,
    flow_version_id     BIGINT UNSIGNED NOT NULL,
    status              VARCHAR(32) NOT NULL,
    current_step_key    VARCHAR(128) NULL,
    started_at          DATETIME(3) NOT NULL,
    ended_at            DATETIME(3) NULL,
    context_json        JSON NULL,
    version             BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_flow_instance_call (tenant_id, call_id),
    KEY idx_flow_instance_status (status, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Runtime flow instance';

CREATE TABLE IF NOT EXISTS fcc_flow_step_execution (
    id                  BIGINT UNSIGNED NOT NULL,
    tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    flow_instance_id    BIGINT UNSIGNED NOT NULL,
    call_id             BIGINT UNSIGNED NOT NULL,
    stage               VARCHAR(32) NULL COMMENT '流水线阶段(TRIGGER, ROUTE, CONNECTED, END)',
    step_key            VARCHAR(128) NOT NULL,
    action_type         VARCHAR(64) NOT NULL,
    attempt_no          INT UNSIGNED NOT NULL DEFAULT 1,
    command_id          VARCHAR(128) NULL,
    trigger_event_id    VARCHAR(128) NULL,
    status              VARCHAR(32) NOT NULL,
    input_json          JSON NULL,
    output_json         JSON NULL,
    error_code          VARCHAR(64) NULL,
    error_message       VARCHAR(1024) NULL,
    started_at          DATETIME(3) NOT NULL,
    ended_at            DATETIME(3) NULL,
    duration_ms         BIGINT UNSIGNED NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_flow_step_attempt (flow_instance_id, step_key, attempt_no),
    KEY idx_flow_step_call (tenant_id, call_id, started_at),
    KEY idx_flow_step_status (status, started_at),
    KEY idx_flow_step_command (command_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Flow action execution audit';

CREATE TABLE IF NOT EXISTS fcc_call_route_attempt (
    id                  BIGINT UNSIGNED NOT NULL,
    tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    call_id             BIGINT UNSIGNED NOT NULL,
    flow_instance_id    BIGINT UNSIGNED NULL,
    sequence_no         INT UNSIGNED NOT NULL,
    route_type          VARCHAR(32) NOT NULL,
    target_type         VARCHAR(32) NOT NULL,
    target_id           VARCHAR(128) NULL,
    strategy            VARCHAR(32) NULL,
    input_value         VARCHAR(128) NULL,
    selected_agent_id   BIGINT UNSIGNED NULL,
    result              VARCHAR(32) NOT NULL,
    failure_reason      VARCHAR(128) NULL,
    started_at          DATETIME(3) NOT NULL,
    ended_at            DATETIME(3) NULL,
    duration_ms         BIGINT UNSIGNED NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_route_call_sequence (call_id, sequence_no),
    KEY idx_route_target_time (tenant_id, target_type, target_id, started_at),
    KEY idx_route_agent_time (selected_agent_id, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Each routing decision and attempt';

CREATE TABLE IF NOT EXISTS fcc_agent_service_session (
    id                      BIGINT UNSIGNED NOT NULL,
    tenant_id               BIGINT UNSIGNED NOT NULL DEFAULT 0,
    call_id                 BIGINT UNSIGNED NOT NULL,
    leg_id                  BIGINT UNSIGNED NULL,
    agent_id                BIGINT UNSIGNED NOT NULL,
    route_attempt_id        BIGINT UNSIGNED NULL,
    sequence_no             INT UNSIGNED NOT NULL,
    service_role            VARCHAR(32) NOT NULL DEFAULT 'PRIMARY',
    transferred_from_id     BIGINT UNSIGNED NULL,
    agent_name_snapshot     VARCHAR(128) NULL,
    work_no_snapshot        VARCHAR(64) NULL,
    endpoint_snapshot       VARCHAR(128) NULL,
    status                  VARCHAR(32) NOT NULL,
    ringing_at              DATETIME(3) NULL,
    answered_at             DATETIME(3) NULL,
    ended_at                DATETIME(3) NULL,
    ring_duration_ms        BIGINT UNSIGNED NULL,
    talk_duration_ms        BIGINT UNSIGNED NULL,
    result                  VARCHAR(32) NULL,
    evaluation_score        SMALLINT UNSIGNED NULL,
    created_at              DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at              DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_agent_service_sequence (call_id, sequence_no),
    KEY idx_agent_service_agent_time (tenant_id, agent_id, created_at),
    KEY idx_agent_service_leg (leg_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Agent participation in a call';

-- -----------------------------------------------------------------------------
-- Business extensions and reliable publication
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS fcc_dial_job (
    id                  BIGINT UNSIGNED NOT NULL,
    tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    owner_work_no       VARCHAR(64) NULL,
    biz_id              VARCHAR(128) NULL,
    job_type            VARCHAR(32) NOT NULL,
    status              VARCHAR(32) NOT NULL,
    scheduled_at        DATETIME(3) NULL,
    max_attempts        INT UNSIGNED NOT NULL DEFAULT 1,
    payload             JSON NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_dial_job_schedule (tenant_id, status, scheduled_at),
    KEY idx_dial_job_biz (tenant_id, biz_id)
    ,UNIQUE KEY uk_dial_job_request(tenant_id,owner_work_no,biz_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Outbound dialing job';

CREATE TABLE IF NOT EXISTS fcc_dial_scheduler_lock(id BIGINT NOT NULL PRIMARY KEY) ENGINE=InnoDB;
INSERT IGNORE INTO fcc_dial_scheduler_lock(id) VALUES(1);

CREATE TABLE IF NOT EXISTS fcc_dial_attempt (
    id                  BIGINT UNSIGNED NOT NULL,
    tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    dial_job_id         BIGINT UNSIGNED NOT NULL,
    call_id             BIGINT UNSIGNED NULL,
    attempt_no          INT UNSIGNED NOT NULL,
    destination_number  VARCHAR(32) NOT NULL,
    status              VARCHAR(32) NOT NULL,
    result              VARCHAR(32) NULL,
    failure_reason      VARCHAR(128) NULL,
    started_at          DATETIME(3) NULL,
    ended_at            DATETIME(3) NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_dial_attempt (dial_job_id, attempt_no),
    KEY idx_dial_attempt_call (call_id),
    KEY idx_dial_attempt_destination (tenant_id, destination_number, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='One outbound dialing attempt';

CREATE TABLE IF NOT EXISTS fcc_callback_task (
    id                  BIGINT UNSIGNED NOT NULL,
    tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    source_call_id      BIGINT UNSIGNED NOT NULL COMMENT '关联原未接通通话ID',
    last_dial_job_id    BIGINT UNSIGNED NULL COMMENT '最近一次持久外呼任务',
    customer_number     VARCHAR(32) NOT NULL COMMENT '客户手机号',
    did_number          VARCHAR(32) NULL COMMENT '进线DID号码',
    missed_at           DATETIME(3) NOT NULL COMMENT '漏话时间',
    missed_reason       VARCHAR(128) NULL COMMENT '漏话原因(坐席忙未接起放弃/排队超时/客户主动挂断等)',
    wait_duration_ms    BIGINT UNSIGNED NULL DEFAULT 0 COMMENT '等待时长毫秒',
    status              VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '状态(PENDING-待办, ASSIGNED-已派单, CALLED-已呼出, COMPLETED-已回访, CANCELLED-已取消)',
    priority            INT NOT NULL DEFAULT 0,
    assignee_agent_id   BIGINT UNSIGNED NULL,
    assignee_work_no    VARCHAR(64) NULL COMMENT '指派跟进坐席工号',
    assignee_name       VARCHAR(128) NULL COMMENT '指派跟进坐席姓名',
    call_attempts       INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '回访呼叫尝试次数',
    last_called_at      DATETIME(3) NULL COMMENT '最后回拨时间',
    notes               VARCHAR(512) NULL COMMENT '跟进备注',
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_callback_source_call (tenant_id, source_call_id),
    KEY idx_callback_job (tenant_id, last_dial_job_id),
    KEY idx_callback_status_time (tenant_id, status, missed_at),
    KEY idx_callback_assignee (tenant_id, assignee_work_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Missed-call callback workflow';

CREATE TABLE IF NOT EXISTS fcc_outbox_event (
    id                  BIGINT UNSIGNED NOT NULL,
    aggregate_type      VARCHAR(64) NOT NULL,
    aggregate_id        VARCHAR(128) NOT NULL,
    event_type          VARCHAR(128) NOT NULL,
    destination         VARCHAR(256) NOT NULL,
    payload             JSON NOT NULL,
    status              VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    retry_count         INT UNSIGNED NOT NULL DEFAULT 0,
    next_retry_at       DATETIME(3) NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    published_at        DATETIME(3) NULL,
    PRIMARY KEY (id),
    KEY idx_outbox_publish (status, next_retry_at, created_at),
    KEY idx_outbox_aggregate (aggregate_type, aggregate_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Transactional outbox';

-- -----------------------------------------------------------------------------
-- System configuration & Fleet governance
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS fcc_system_config (
    id                  BIGINT UNSIGNED NOT NULL,
    tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    prop_name           VARCHAR(128) NOT NULL,
    prop_value          TEXT NOT NULL,
    prop_type           VARCHAR(32) NOT NULL DEFAULT 'STRING',
    scope               VARCHAR(32) NOT NULL DEFAULT 'BACKEND' COMMENT 'WEB, BACKEND, CLIENT, SYSTEM',
    description         VARCHAR(255) NULL,
    created_by          VARCHAR(64) NULL,
    updated_by          VARCHAR(64) NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_config_tenant_scope_prop (tenant_id, scope, prop_name),
    KEY idx_config_scope (tenant_id, scope)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Dynamic system business configuration';

CREATE TABLE IF NOT EXISTS fcc_client_version_release (
    id                  BIGINT UNSIGNED NOT NULL,
    tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    version             VARCHAR(32) NOT NULL,
    platform            VARCHAR(32) NOT NULL DEFAULT 'WINDOWS' COMMENT 'WINDOWS, MAC, LINUX, WEB',
    download_url        VARCHAR(512) NOT NULL,
    file_md5            VARCHAR(64) NULL,
    force_update        TINYINT(1) NOT NULL DEFAULT 0,
    status              VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT, RELEASED, DEPRECATED',
    release_notes       TEXT NULL,
    released_at         DATETIME(3) NULL,
    created_by          VARCHAR(64) NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_version_tenant_platform (tenant_id, platform, version),
    KEY idx_version_status (tenant_id, platform, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='PC client version release and auto-update';

CREATE TABLE IF NOT EXISTS fcc_client_hardware_record (
    id                  BIGINT UNSIGNED NOT NULL,
    tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    agent_id            BIGINT UNSIGNED NOT NULL,
    work_num            VARCHAR(32) NOT NULL,
    client_version      VARCHAR(32) NOT NULL,
    mac_addr            VARCHAR(64) NOT NULL,
    disk_seq            VARCHAR(128) NULL,
    cpu_seq             VARCHAR(128) NULL,
    bios_seq            VARCHAR(128) NULL,
    os                  VARCHAR(128) NULL,
    ip_addr             VARCHAR(64) NULL,
    login_time          DATETIME(3) NOT NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_hardware_agent_login (tenant_id, agent_id, login_time),
    KEY idx_hardware_mac (tenant_id, mac_addr)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Agent client hardware fingerprint audit';

CREATE TABLE IF NOT EXISTS fcc_agent_substitute_record (
    id                  BIGINT UNSIGNED NOT NULL,
    tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    applicant_agent_id  BIGINT UNSIGNED NOT NULL,
    substitute_agent_id BIGINT UNSIGNED NOT NULL,
    substitute_type     VARCHAR(32) NOT NULL DEFAULT 'PP' COMMENT 'PP: Agent-to-Agent, PG: Agent-to-Group',
    scope               VARCHAR(32) NOT NULL DEFAULT 'NIGHT_OFF' COMMENT 'NIGHT_OFF, TEMPORARY_LEAVE',
    start_time          DATETIME(3) NOT NULL,
    end_time            DATETIME(3) NOT NULL,
    priority            INT NOT NULL DEFAULT 99,
    status              VARCHAR(32) NOT NULL DEFAULT 'UNCONFIRM' COMMENT 'UNCONFIRM, CONFIRMED, CANCELLED',
    reason              VARCHAR(255) NULL,
    confirmed_at        DATETIME(3) NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_substitute_applicant (tenant_id, applicant_agent_id, start_time, end_time),
    KEY idx_substitute_agent (tenant_id, substitute_agent_id, start_time, end_time),
    KEY idx_substitute_status (tenant_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Agent shift substitution and night transfer';


