-- FCC initial schema
-- Fresh-install schema for one independently deployed call center.
CREATE TABLE IF NOT EXISTS fcc_screen_pop_delivery (
 owner_work_no VARCHAR(64) NOT NULL,
 call_id BIGINT UNSIGNED NOT NULL,
 payload JSON NOT NULL,
 expires_at DATETIME(3) NOT NULL,
 received_at DATETIME(3) NULL,
 shown_at DATETIME(3) NULL,
 activated_at DATETIME(3) NULL,
 unsupported_at DATETIME(3) NULL,
 closed_at DATETIME(3) NULL,
 PRIMARY KEY(owner_work_no,call_id),
 KEY idx_pop_owner_expiry(owner_work_no,closed_at,expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS fcc_event_inbox (
    event_id       CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    node_id        VARCHAR(128) NOT NULL,
    payload        JSON NOT NULL,
    status         VARCHAR(16) NOT NULL,
    attempt_count  INT UNSIGNED NOT NULL DEFAULT 1,
    last_error     VARCHAR(128) NULL,
    created_at     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (event_id),
    KEY idx_inbox_status_time (status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- This new project supports fresh installation only; rebuild the database after baseline changes.
CREATE TABLE IF NOT EXISTS fcc_customer (
 id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
 owner_work_no VARCHAR(64) NOT NULL,
 name VARCHAR(128) NOT NULL,
 phone_number VARCHAR(32) NOT NULL,
 company_name VARCHAR(255) NULL,
 notes TEXT NULL,
 version BIGINT UNSIGNED NOT NULL DEFAULT 0,
 created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 KEY idx_customer_owner_page(owner_work_no,id),
 KEY idx_customer_owner_phone(owner_work_no,phone_number,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Database: MySQL 8.0+
-- Time policy: application writes UTC; datetime precision is milliseconds.
-- ID policy: BIGINT IDs are generated by the application (Snowflake/segment).
-- Foreign keys are intentionally logical to support high-volume writes, partitioning
-- and online archiving. Unique keys and application transactions enforce integrity.

SET NAMES utf8mb4;
SET time_zone = '+00:00';

-- -----------------------------------------------------------------------------
-- Telephony resources
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS fcc_telephony_node (
    id                  BIGINT UNSIGNED NOT NULL,
    node_id             VARCHAR(128) NOT NULL,
    cluster_id          VARCHAR(64) NOT NULL DEFAULT 'default',
    host                VARCHAR(255) NULL,
    zone                VARCHAR(64) NULL,
    status              VARCHAR(32) NOT NULL DEFAULT 'OFFLINE',
    max_channels        INT UNSIGNED NOT NULL DEFAULT 0,
    active_channels     INT UNSIGNED NOT NULL DEFAULT 0,
    draining_since      DATETIME(3) NULL,
    last_heartbeat_at   DATETIME(3) NULL,
    metadata            JSON NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_node_node_id (node_id),
    KEY idx_node_status_heartbeat (status, last_heartbeat_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='FreeSWITCH/Sidecar node registry';

CREATE TABLE IF NOT EXISTS fcc_telephony_trunk (
    id                  BIGINT UNSIGNED NOT NULL,
    trunk_code          VARCHAR(64) NOT NULL,
    trunk_name          VARCHAR(128) NOT NULL,
    carrier_code        VARCHAR(64) NULL,
    gateway_name        VARCHAR(128) NOT NULL,
    direction           VARCHAR(16) NOT NULL DEFAULT 'BOTH',
    status              VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    max_concurrent      INT UNSIGNED NOT NULL DEFAULT 0,
    config_json         JSON NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at          DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_trunk_code (trunk_code),
    KEY idx_trunk_gateway (gateway_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='SIP trunk and carrier gateway';

CREATE TABLE IF NOT EXISTS fcc_did_number (
    id                  BIGINT UNSIGNED NOT NULL,
    trunk_id            BIGINT UNSIGNED NULL,
    phone_number        VARCHAR(32) NOT NULL,
    route_key           VARCHAR(128) NULL,
    status              VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at          DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_did_number (phone_number),
    KEY idx_did_trunk (trunk_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Inbound DID number';

CREATE TABLE IF NOT EXISTS fcc_outbound_number (
    id                  BIGINT UNSIGNED NOT NULL,
    trunk_id            BIGINT UNSIGNED NOT NULL,
    phone_number        VARCHAR(32) NOT NULL,
    pool_code           VARCHAR(64) NOT NULL DEFAULT 'default',
    status              VARCHAR(32) NOT NULL DEFAULT 'AVAILABLE',
    max_concurrent      INT UNSIGNED NOT NULL DEFAULT 1,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at          DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_outbound_number (phone_number),
    KEY idx_outbound_pool_status (pool_code, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Outbound caller number pool';

CREATE TABLE IF NOT EXISTS fcc_extension (
    id                  BIGINT UNSIGNED NOT NULL,
    extension           VARCHAR(32) NOT NULL,
    endpoint_type       VARCHAR(32) NOT NULL DEFAULT 'SIP',
    credential_secret   VARBINARY(512) NULL,
    status              VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    agent_work_no       VARCHAR(64) NULL COMMENT '当前绑定的坐席工号',
    agent_name          VARCHAR(128) NULL COMMENT '当前绑定的坐席姓名',
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at          DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_extension_number (extension),
    KEY idx_ext_agent_work_no (agent_work_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='SIP/WebRTC extension';

CREATE TABLE IF NOT EXISTS fcc_endpoint_registration_event (
    id                  BIGINT UNSIGNED NOT NULL,
    extension_id        BIGINT UNSIGNED NULL,
    extension           VARCHAR(32) NOT NULL,
    protocol            VARCHAR(16) NOT NULL,
    status              VARCHAR(32) NOT NULL,
    contact             VARCHAR(512) NULL,
    user_agent          VARCHAR(512) NULL,
    network_ip          VARCHAR(64) NULL,
    network_port        INT UNSIGNED NULL,
    node_id             VARCHAR(128) NULL,
    occurred_at         DATETIME(3) NOT NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_registration_extension_time (extension, occurred_at),
    KEY idx_registration_node_time (node_id, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Append-only endpoint registration history';

-- -----------------------------------------------------------------------------
-- Agent domain
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS fcc_agent (
    id                    BIGINT UNSIGNED NOT NULL,
    work_no               VARCHAR(64) NOT NULL,
    agent_name            VARCHAR(128) NOT NULL,
    phone_number          VARCHAR(32) NULL,
    role_code             VARCHAR(64) NULL,
    status                VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    password_hash         VARCHAR(255) NULL COMMENT '坐席登录口令派生串 pbkdf2-sha256$iterations$salt$hash，为空表示禁止登录',
    password_updated_at   DATETIME(3) NULL COMMENT '口令最近一次设置时间',
    last_login_at         DATETIME(3) NULL COMMENT '最近一次成功登录时间',
    metadata              JSON NULL,
    created_at            DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at            DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at            DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_agent_work_no (work_no),
    KEY idx_agent_phone (phone_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Agent master data';

-- -----------------------------------------------------------------------------
-- Console accounts
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS fcc_admin_user (
    id                    BIGINT UNSIGNED NOT NULL,
    username              VARCHAR(64) NOT NULL COMMENT '管理控制台登录账号',
    real_name             VARCHAR(128) NOT NULL COMMENT '账号显示姓名',
    password_hash         VARCHAR(255) NOT NULL COMMENT '口令派生串 pbkdf2-sha256$iterations$salt$hash',
    password_updated_at   DATETIME(3) NULL COMMENT '口令最近一次设置时间',
    role_code             VARCHAR(64) NOT NULL DEFAULT 'ADMIN' COMMENT '控制台角色: ADMIN / OPERATOR / AUDITOR',
    status                VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT 'ENABLED / DISABLED',
    last_login_at         DATETIME(3) NULL COMMENT '最近一次成功登录时间',
    created_at            DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at            DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at            DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_admin_user_username (username),
    KEY idx_admin_user_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Management console account';

CREATE TABLE IF NOT EXISTS fcc_agent_group (
    id                  BIGINT UNSIGNED NOT NULL,
    parent_id           BIGINT UNSIGNED NULL,
    group_code          VARCHAR(64) NOT NULL,
    group_name          VARCHAR(128) NOT NULL,
    group_type          VARCHAR(32) NOT NULL DEFAULT 'SKILL',
    routing_strategy    VARCHAR(32) NOT NULL DEFAULT 'LONGEST_IDLE',
    status              VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at          DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_group_code (group_code),
    KEY idx_group_parent (parent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Agent skill group';

CREATE TABLE IF NOT EXISTS fcc_agent_group_member (
    id                  BIGINT UNSIGNED NOT NULL,
    group_id            BIGINT UNSIGNED NOT NULL,
    agent_id            BIGINT UNSIGNED NOT NULL,
    member_role         VARCHAR(32) NOT NULL DEFAULT 'MEMBER',
    priority            INT NOT NULL DEFAULT 0,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at          DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_group_member (group_id, agent_id),
    KEY idx_group_member_agent (agent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Agent and skill group membership';

CREATE TABLE IF NOT EXISTS fcc_agent_endpoint_binding (
    id                  BIGINT UNSIGNED NOT NULL,
    agent_id            BIGINT UNSIGNED NOT NULL,
    endpoint_type       VARCHAR(32) NOT NULL,
    extension_id        BIGINT UNSIGNED NULL,
    endpoint_value      VARCHAR(128) NULL,
    priority            INT NOT NULL DEFAULT 0,
    is_active           TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否为坐席当前接听终端',
    status              VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    active_agent_id     BIGINT UNSIGNED GENERATED ALWAYS AS (
        CASE WHEN is_active = 1 AND status = 'ENABLED' THEN agent_id ELSE NULL END
    ) STORED,
    enabled_binding_key VARCHAR(512) GENERATED ALWAYS AS (
        CASE WHEN status = 'ENABLED'
             THEN CONCAT(agent_id, ':', endpoint_type, ':', COALESCE(endpoint_value, ''))
             ELSE NULL END
    ) STORED,
    enabled_sip_value   VARCHAR(128) GENERATED ALWAYS AS (
        CASE WHEN status = 'ENABLED' AND endpoint_type = 'SIP' THEN endpoint_value ELSE NULL END
    ) STORED,
    valid_from          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    valid_to            DATETIME(3) NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_binding_active_agent (active_agent_id),
    UNIQUE KEY uk_binding_enabled_identity (enabled_binding_key),
    UNIQUE KEY uk_binding_enabled_sip (enabled_sip_value),
    KEY idx_binding_agent_status (agent_id, status),
    KEY idx_binding_endpoint_status (endpoint_type, endpoint_value, status),
    KEY idx_binding_extension (extension_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Agent endpoint binding history';

CREATE TABLE IF NOT EXISTS fcc_agent_endpoint_selection_audit (
    id                  BIGINT UNSIGNED NOT NULL,
    agent_id            BIGINT UNSIGNED NOT NULL,
    actor               VARCHAR(128) NOT NULL,
    old_binding_id      BIGINT UNSIGNED NULL,
    new_binding_id      BIGINT UNSIGNED NOT NULL,
    result              VARCHAR(32) NOT NULL,
    reason              VARCHAR(512) NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_endpoint_audit_agent_time (agent_id, created_at),
    KEY idx_endpoint_audit_actor_time (actor, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Agent active endpoint selection audit';

CREATE TABLE IF NOT EXISTS fcc_agent_presence (
    agent_id            BIGINT UNSIGNED NOT NULL,
    login_status        VARCHAR(32) NOT NULL DEFAULT 'OFFLINE',
    work_status         VARCHAR(32) NOT NULL DEFAULT 'READY',
    answer_type         VARCHAR(32) NULL,
    active_call_id      BIGINT UNSIGNED NULL,
    login_at            DATETIME(3) NULL,
    last_state_at       DATETIME(3) NOT NULL,
    version             BIGINT UNSIGNED NOT NULL DEFAULT 0,
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (agent_id),
    KEY idx_presence_dispatch (login_status, work_status, last_state_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Current agent presence snapshot';

CREATE TABLE IF NOT EXISTS fcc_agent_state_interval (
    id                  BIGINT UNSIGNED NOT NULL,
    agent_id            BIGINT UNSIGNED NOT NULL,
    state_type          VARCHAR(32) NOT NULL,
    state_value         VARCHAR(32) NOT NULL,
    started_at          DATETIME(3) NOT NULL,
    ended_at            DATETIME(3) NULL,
    duration_ms         BIGINT UNSIGNED NULL,
    source              VARCHAR(32) NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_agent_state_time (agent_id, started_at),
    KEY idx_agent_state_open (agent_id, ended_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Agent state interval facts';

-- -----------------------------------------------------------------------------
-- Call facts: Call -> Leg -> Bridge, Event and Command
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS fcc_call_session (
    id                  BIGINT UNSIGNED NOT NULL,
    biz_id              VARCHAR(128) NULL,
    ctrl_id             VARCHAR(128) NOT NULL,
    model_type          VARCHAR(64) NOT NULL,
    flow_code           VARCHAR(64) NULL COMMENT '绑定的流程编码(如 FLOW-INBOUND)',
    route_target_type   VARCHAR(32) NULL COMMENT '目标类型(AGENT, GROUP)',
    route_target_id     VARCHAR(64) NULL COMMENT '目标标识(工号/组ID)',
    direction           VARCHAR(16) NOT NULL,
    caller_number       VARCHAR(32) NULL,
    destination_number  VARCHAR(32) NULL,
    status              VARCHAR(32) NOT NULL,
    result              VARCHAR(32) NULL,
    started_at          DATETIME(3) NOT NULL,
    ringing_at          DATETIME(3) NULL,
    answered_at         DATETIME(3) NULL,
    ended_at            DATETIME(3) NULL,
    ring_duration_ms    BIGINT UNSIGNED NULL,
    talk_duration_ms    BIGINT UNSIGNED NULL,
    audio_duration_sec  INT UNSIGNED NULL DEFAULT 0 COMMENT '净通话时长(秒)',
    total_duration_ms   BIGINT UNSIGNED NULL,
    hangup_cause        VARCHAR(64) NULL,
    hangup_initiator    VARCHAR(32) NULL,
    primary_agent_id    BIGINT UNSIGNED NULL,
    primary_work_no     VARCHAR(64) NULL,
    agent_work_no       VARCHAR(64) NULL COMMENT '接听坐席工号',
    agent_name          VARCHAR(128) NULL COMMENT '接听坐席姓名',
    evaluation_score    SMALLINT UNSIGNED NULL,
    record_file_id      VARCHAR(128) NULL COMMENT '录音文件标识或路径',
    attributes          JSON NULL,
    version             BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_call_ctrl (ctrl_id),
    KEY idx_call_biz (biz_id),
    KEY idx_call_status_started (status, started_at),
    KEY idx_call_caller_started (caller_number, started_at),
    KEY idx_call_destination_started (destination_number, started_at),
    KEY idx_call_agent_started (primary_agent_id, started_at),
    KEY idx_call_eval_started (evaluation_score, started_at),
    KEY idx_cs_agent_work_no (agent_work_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Business call aggregate';

CREATE TABLE IF NOT EXISTS fcc_call_leg (
    id                  BIGINT UNSIGNED NOT NULL,
    call_id             BIGINT UNSIGNED NOT NULL,
    channel_uuid        VARCHAR(64) NOT NULL,
    node_id             VARCHAR(128) NOT NULL,
    parent_leg_id       BIGINT UNSIGNED NULL,
    role_type           VARCHAR(32) NOT NULL,
    direction           VARCHAR(16) NOT NULL,
    endpoint_type       VARCHAR(32) NULL,
    endpoint_id         VARCHAR(128) NULL,
    caller_number       VARCHAR(32) NULL,
    destination_number  VARCHAR(32) NULL,
    trunk_id            BIGINT UNSIGNED NULL,
    gateway_name        VARCHAR(128) NULL,
    state               VARCHAR(32) NOT NULL,
    attempt_no          INT UNSIGNED NOT NULL DEFAULT 1,
    created_time        DATETIME(3) NOT NULL,
    ringing_at          DATETIME(3) NULL,
    answered_at         DATETIME(3) NULL,
    bridged_at          DATETIME(3) NULL,
    ended_at            DATETIME(3) NULL,
    ring_duration_ms    BIGINT UNSIGNED NULL,
    talk_duration_ms    BIGINT UNSIGNED NULL,
    hangup_cause        VARCHAR(64) NULL,
    sip_status          INT UNSIGNED NULL,
    metadata            JSON NULL,
    version             BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_leg_channel_uuid (channel_uuid),
    KEY idx_leg_call_role (call_id, role_type),
    KEY idx_leg_node_state (node_id, state),
    KEY idx_leg_parent (parent_leg_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='FreeSWITCH channel/leg fact';

CREATE TABLE IF NOT EXISTS fcc_call_bridge (
    id                  BIGINT UNSIGNED NOT NULL,
    call_id             BIGINT UNSIGNED NOT NULL,
    bridge_uuid         VARCHAR(64) NOT NULL,
    bridge_type         VARCHAR(32) NOT NULL DEFAULT 'DIRECT',
    started_at          DATETIME(3) NOT NULL,
    ended_at            DATETIME(3) NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_bridge_uuid (bridge_uuid),
    KEY idx_bridge_call_time (call_id, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Time-scoped media bridge';

CREATE TABLE IF NOT EXISTS fcc_call_bridge_member (
    id                  BIGINT UNSIGNED NOT NULL,
    bridge_id           BIGINT UNSIGNED NOT NULL,
    leg_id              BIGINT UNSIGNED NOT NULL,
    joined_at           DATETIME(3) NOT NULL,
    left_at             DATETIME(3) NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_bridge_member_join (bridge_id, leg_id, joined_at),
    KEY idx_bridge_member_leg (leg_id, joined_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Bridge leg membership';

CREATE TABLE IF NOT EXISTS fcc_call_event (
    id                  BIGINT UNSIGNED NOT NULL,
    event_id            VARCHAR(128) NOT NULL,
    node_id             VARCHAR(128) NOT NULL,
    call_id             BIGINT UNSIGNED NULL,
    leg_id              BIGINT UNSIGNED NULL,
    channel_uuid        VARCHAR(64) NULL,
    event_type          VARCHAR(64) NOT NULL,
    event_sequence      BIGINT UNSIGNED NULL,
    event_time          DATETIME(3) NOT NULL,
    received_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    normalized_payload  JSON NULL,
    raw_payload         JSON NULL,
    process_status      VARCHAR(32) NOT NULL DEFAULT 'RECEIVED',
    process_error       VARCHAR(1024) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_event_id (event_id),
    KEY idx_event_call_time (call_id, event_time),
    KEY idx_event_leg_time (leg_id, event_time),
    KEY idx_event_channel_time (channel_uuid, event_time),
    KEY idx_event_process (process_status, received_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Append-only normalized and raw telephony event';

CREATE TABLE IF NOT EXISTS fcc_call_command (
    id                  BIGINT UNSIGNED NOT NULL,
    command_id          VARCHAR(128) NOT NULL,
    idempotency_key     VARCHAR(128) NOT NULL,
    call_id             BIGINT UNSIGNED NULL,
    leg_id              BIGINT UNSIGNED NULL,
    assigned_node_id    VARCHAR(128) NULL COMMENT 'Sidecar 接受命令后返回的实际执行节点；发送前未知',
    method_name         VARCHAR(64) NOT NULL,
    request_payload     JSON NULL,
    response_payload    JSON NULL,
    status              VARCHAR(32) NOT NULL DEFAULT 'CREATED',
    error_code          VARCHAR(64) NULL,
    error_message       VARCHAR(1024) NULL,
    retry_count         INT UNSIGNED NOT NULL DEFAULT 0,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    sent_at             DATETIME(3) NULL,
    completed_at        DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_command_id (command_id),
    UNIQUE KEY uk_command_idempotency (idempotency_key),
    KEY idx_command_call_created (call_id, created_at),
    KEY idx_command_status_created (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='FCC FNode command audit and idempotency';

CREATE TABLE IF NOT EXISTS fcc_call_recording (
    id                  BIGINT UNSIGNED NOT NULL,
    recording_id        VARCHAR(128) NOT NULL,
    call_id             BIGINT UNSIGNED NOT NULL,
    leg_id              BIGINT UNSIGNED NULL,
    bridge_id           BIGINT UNSIGNED NULL,
    node_id             VARCHAR(128) NULL COMMENT '写出该录音文件的 Sidecar/FreeSWITCH 节点',
    status              VARCHAR(32) NOT NULL,
    storage_type        VARCHAR(32) NOT NULL DEFAULT 'OBJECT_STORAGE',
    bucket_name         VARCHAR(128) NULL,
    object_key          VARCHAR(512) NOT NULL COMMENT '录音文件地址: 共享存储绝对路径，或远端对象存储 URL',
    media_format        VARCHAR(32) NULL,
    size_bytes          BIGINT UNSIGNED NULL,
    duration_ms         BIGINT UNSIGNED NULL,
    checksum            VARCHAR(128) NULL,
    started_at          DATETIME(3) NULL,
    completed_at        DATETIME(3) NULL,
    retain_until        DATETIME(3) NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_recording_id (recording_id),
    KEY idx_recording_call (call_id),
    KEY idx_recording_retain (retain_until)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Call recording metadata';

-- -----------------------------------------------------------------------------
-- Flow and routing
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS fcc_flow_definition (
    id                  BIGINT UNSIGNED NOT NULL,
    flow_key            VARCHAR(128) NOT NULL,
    flow_name           VARCHAR(128) NOT NULL,
    model_type          VARCHAR(64) NOT NULL,
    status              VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    current_version     INT UNSIGNED NOT NULL DEFAULT 0,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at          DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_flow_key (flow_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Flow definition identity';

CREATE TABLE IF NOT EXISTS fcc_flow_definition_version (
    id                  BIGINT UNSIGNED NOT NULL,
    flow_definition_id  BIGINT UNSIGNED NOT NULL,
    version_no          INT UNSIGNED NOT NULL,
    definition_json     JSON NOT NULL,
    checksum            VARCHAR(128) NOT NULL,
    publish_status      VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    published_at        DATETIME(3) NULL,
    created_by          VARCHAR(128) NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_flow_version (flow_definition_id, version_no),
    KEY idx_flow_version_publish (flow_definition_id, publish_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Immutable flow definition version';

CREATE TABLE IF NOT EXISTS fcc_flow_instance (
    id                  BIGINT UNSIGNED NOT NULL,
    call_id             BIGINT UNSIGNED NOT NULL,
    flow_definition_id  BIGINT UNSIGNED NOT NULL,
    flow_version_id     BIGINT UNSIGNED NOT NULL,
    status              VARCHAR(32) NOT NULL,
    current_step_key    VARCHAR(128) NULL,
    started_at          DATETIME(3) NOT NULL,
    ended_at            DATETIME(3) NULL,
    context_json        JSON NULL,
    version             BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_flow_instance_call (call_id),
    KEY idx_flow_instance_status (status, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Runtime flow instance';

CREATE TABLE IF NOT EXISTS fcc_flow_step_execution (
    id                  BIGINT UNSIGNED NOT NULL,
    flow_instance_id    BIGINT UNSIGNED NOT NULL,
    call_id             BIGINT UNSIGNED NOT NULL,
    stage               VARCHAR(32) NULL COMMENT '流水线阶段(TRIGGER, ROUTE, CONNECTED, END)',
    step_key            VARCHAR(128) NOT NULL,
    action_type         VARCHAR(64) NOT NULL,
    attempt_no          INT UNSIGNED NOT NULL DEFAULT 1,
    command_id          VARCHAR(128) NULL,
    trigger_event_id    VARCHAR(128) NULL,
    status              VARCHAR(32) NOT NULL,
    input_json          JSON NULL,
    output_json         JSON NULL,
    error_code          VARCHAR(64) NULL,
    error_message       VARCHAR(1024) NULL,
    started_at          DATETIME(3) NOT NULL,
    ended_at            DATETIME(3) NULL,
    duration_ms         BIGINT UNSIGNED NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_flow_step_attempt (flow_instance_id, step_key, attempt_no),
    KEY idx_flow_step_call (call_id, started_at),
    KEY idx_flow_step_status (status, started_at),
    KEY idx_flow_step_command (command_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Flow action execution audit';

CREATE TABLE IF NOT EXISTS fcc_call_route_attempt (
    id                  BIGINT UNSIGNED NOT NULL,
    call_id             BIGINT UNSIGNED NOT NULL,
    flow_instance_id    BIGINT UNSIGNED NULL,
    sequence_no         INT UNSIGNED NOT NULL,
    route_type          VARCHAR(32) NOT NULL,
    target_type         VARCHAR(32) NOT NULL,
    target_id           VARCHAR(128) NULL,
    strategy            VARCHAR(32) NULL,
    input_value         VARCHAR(128) NULL,
    selected_agent_id   BIGINT UNSIGNED NULL,
    result              VARCHAR(32) NOT NULL,
    failure_reason      VARCHAR(128) NULL,
    started_at          DATETIME(3) NOT NULL,
    ended_at            DATETIME(3) NULL,
    duration_ms         BIGINT UNSIGNED NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_route_call_sequence (call_id, sequence_no),
    KEY idx_route_target_time (target_type, target_id, started_at),
    KEY idx_route_agent_time (selected_agent_id, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Each routing decision and attempt';

CREATE TABLE IF NOT EXISTS fcc_agent_service_session (
    id                      BIGINT UNSIGNED NOT NULL,
    call_id                 BIGINT UNSIGNED NOT NULL,
    leg_id                  BIGINT UNSIGNED NULL,
    agent_id                BIGINT UNSIGNED NOT NULL,
    route_attempt_id        BIGINT UNSIGNED NULL,
    sequence_no             INT UNSIGNED NOT NULL,
    service_role            VARCHAR(32) NOT NULL DEFAULT 'PRIMARY',
    transferred_from_id     BIGINT UNSIGNED NULL,
    agent_name_snapshot     VARCHAR(128) NULL,
    work_no_snapshot        VARCHAR(64) NULL,
    endpoint_snapshot       VARCHAR(128) NULL,
    status                  VARCHAR(32) NOT NULL,
    ringing_at              DATETIME(3) NULL,
    answered_at             DATETIME(3) NULL,
    ended_at                DATETIME(3) NULL,
    ring_duration_ms        BIGINT UNSIGNED NULL,
    talk_duration_ms        BIGINT UNSIGNED NULL,
    result                  VARCHAR(32) NULL,
    evaluation_score        SMALLINT UNSIGNED NULL,
    created_at              DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at              DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_agent_service_sequence (call_id, sequence_no),
    KEY idx_agent_service_agent_time (agent_id, created_at),
    KEY idx_agent_service_leg (leg_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Agent participation in a call';

-- -----------------------------------------------------------------------------
-- Business extensions and reliable publication
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS fcc_dial_job (
    id                  BIGINT UNSIGNED NOT NULL,
    owner_work_no       VARCHAR(64) NULL,
    biz_id              VARCHAR(128) NULL,
    job_type            VARCHAR(32) NOT NULL,
    status              VARCHAR(32) NOT NULL,
    scheduled_at        DATETIME(3) NULL,
    max_attempts        INT UNSIGNED NOT NULL DEFAULT 1,
    payload             JSON NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_dial_job_schedule (status, scheduled_at),
    KEY idx_dial_job_biz (biz_id),
    UNIQUE KEY uk_dial_job_request(owner_work_no,biz_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Outbound dialing job';

CREATE TABLE IF NOT EXISTS fcc_dial_scheduler_lock(id BIGINT NOT NULL PRIMARY KEY) ENGINE=InnoDB;
INSERT IGNORE INTO fcc_dial_scheduler_lock(id) VALUES(1);

CREATE TABLE IF NOT EXISTS fcc_dial_attempt (
    id                  BIGINT UNSIGNED NOT NULL,
    dial_job_id         BIGINT UNSIGNED NOT NULL,
    call_id             BIGINT UNSIGNED NULL,
    attempt_no          INT UNSIGNED NOT NULL,
    destination_number  VARCHAR(32) NOT NULL,
    status              VARCHAR(32) NOT NULL,
    result              VARCHAR(32) NULL,
    failure_reason      VARCHAR(128) NULL,
    started_at          DATETIME(3) NULL,
    ended_at            DATETIME(3) NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_dial_attempt (dial_job_id, attempt_no),
    KEY idx_dial_attempt_call (call_id),
    KEY idx_dial_attempt_destination (destination_number, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='One outbound dialing attempt';

CREATE TABLE IF NOT EXISTS fcc_callback_task (
    id                  BIGINT UNSIGNED NOT NULL,
    source_call_id      BIGINT UNSIGNED NOT NULL COMMENT '关联原未接通通话ID',
    last_dial_job_id    BIGINT UNSIGNED NULL COMMENT '最近一次持久外呼任务',
    customer_number     VARCHAR(32) NOT NULL COMMENT '客户手机号',
    did_number          VARCHAR(32) NULL COMMENT '进线DID号码',
    missed_at           DATETIME(3) NOT NULL COMMENT '漏话时间',
    missed_reason       VARCHAR(128) NULL COMMENT '漏话原因(坐席忙未接起放弃/排队超时/客户主动挂断等)',
    wait_duration_ms    BIGINT UNSIGNED NULL DEFAULT 0 COMMENT '等待时长毫秒',
    status              VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '状态(PENDING-待办, ASSIGNED-已派单, CALLED-已呼出, COMPLETED-已回访, CANCELLED-已取消)',
    priority            INT NOT NULL DEFAULT 0,
    assignee_agent_id   BIGINT UNSIGNED NULL,
    assignee_work_no    VARCHAR(64) NULL COMMENT '指派跟进坐席工号',
    assignee_name       VARCHAR(128) NULL COMMENT '指派跟进坐席姓名',
    call_attempts       INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '回访呼叫尝试次数',
    last_called_at      DATETIME(3) NULL COMMENT '最后回拨时间',
    notes               VARCHAR(512) NULL COMMENT '跟进备注',
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_callback_source_call (source_call_id),
    KEY idx_callback_job (last_dial_job_id),
    KEY idx_callback_status_time (status, missed_at),
    KEY idx_callback_assignee (assignee_work_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Missed-call callback workflow';

CREATE TABLE IF NOT EXISTS fcc_outbox_event (
    id                  BIGINT UNSIGNED NOT NULL,
    aggregate_type      VARCHAR(64) NOT NULL,
    aggregate_id        VARCHAR(128) NOT NULL,
    event_type          VARCHAR(128) NOT NULL,
    destination         VARCHAR(256) NOT NULL,
    payload             JSON NOT NULL,
    status              VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    retry_count         INT UNSIGNED NOT NULL DEFAULT 0,
    next_retry_at       DATETIME(3) NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    published_at        DATETIME(3) NULL,
    PRIMARY KEY (id),
    KEY idx_outbox_publish (status, next_retry_at, created_at),
    KEY idx_outbox_aggregate (aggregate_type, aggregate_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Transactional outbox';

-- -----------------------------------------------------------------------------
-- System configuration & Fleet governance
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS fcc_system_config (
    id                  BIGINT UNSIGNED NOT NULL,
    prop_name           VARCHAR(128) NOT NULL,
    prop_value          TEXT NOT NULL,
    prop_type           VARCHAR(32) NOT NULL DEFAULT 'STRING',
    scope               VARCHAR(32) NOT NULL DEFAULT 'BACKEND' COMMENT 'WEB, BACKEND, CLIENT, SYSTEM',
    description         VARCHAR(255) NULL,
    created_by          VARCHAR(64) NULL,
    updated_by          VARCHAR(64) NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_config_scope_prop (scope, prop_name),
    KEY idx_config_scope (scope)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Dynamic system business configuration';

CREATE TABLE IF NOT EXISTS fcc_client_version_release (
    id                  BIGINT UNSIGNED NOT NULL,
    version             VARCHAR(32) NOT NULL,
    platform            VARCHAR(32) NOT NULL DEFAULT 'WINDOWS' COMMENT 'WINDOWS, MAC, LINUX, WEB',
    download_url        VARCHAR(512) NOT NULL,
    file_md5            VARCHAR(64) NULL,
    force_update        TINYINT(1) NOT NULL DEFAULT 0,
    status              VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT, RELEASED, DEPRECATED',
    release_notes       TEXT NULL,
    released_at         DATETIME(3) NULL,
    created_by          VARCHAR(64) NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_version_platform (platform, version),
    KEY idx_version_status (platform, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='PC client version release and auto-update';

CREATE TABLE IF NOT EXISTS fcc_client_hardware_record (
    id                  BIGINT UNSIGNED NOT NULL,
    agent_id            BIGINT UNSIGNED NOT NULL,
    work_num            VARCHAR(32) NOT NULL,
    client_version      VARCHAR(32) NOT NULL,
    mac_addr            VARCHAR(64) NOT NULL,
    disk_seq            VARCHAR(128) NULL,
    cpu_seq             VARCHAR(128) NULL,
    bios_seq            VARCHAR(128) NULL,
    os                  VARCHAR(128) NULL,
    ip_addr             VARCHAR(64) NULL,
    login_time          DATETIME(3) NOT NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_hardware_agent_login (agent_id, login_time),
    KEY idx_hardware_mac (mac_addr)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Agent client hardware fingerprint audit';

CREATE TABLE IF NOT EXISTS fcc_agent_substitute_record (
    id                  BIGINT UNSIGNED NOT NULL,
    applicant_agent_id  BIGINT UNSIGNED NOT NULL,
    substitute_agent_id BIGINT UNSIGNED NOT NULL,
    substitute_type     VARCHAR(32) NOT NULL DEFAULT 'PP' COMMENT 'PP: Agent-to-Agent, PG: Agent-to-Group',
    scope               VARCHAR(32) NOT NULL DEFAULT 'NIGHT_OFF' COMMENT 'NIGHT_OFF, TEMPORARY_LEAVE',
    start_time          DATETIME(3) NOT NULL,
    end_time            DATETIME(3) NOT NULL,
    priority            INT NOT NULL DEFAULT 99,
    status              VARCHAR(32) NOT NULL DEFAULT 'UNCONFIRM' COMMENT 'UNCONFIRM, CONFIRMED, CANCELLED',
    reason              VARCHAR(255) NULL,
    confirmed_at        DATETIME(3) NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_substitute_applicant (applicant_agent_id, start_time, end_time),
    KEY idx_substitute_agent (substitute_agent_id, start_time, end_time),
    KEY idx_substitute_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Agent shift substitution and night transfer';

-- BEGIN GENERATED COMPLETE SYSTEM MODELS
-- Generated from fcc-common/src/main/resources/flows/system-models.json.

-- Fresh-install seed for the single-call-center schema.

START TRANSACTION;

INSERT INTO fcc_flow_definition(id,flow_key,flow_name,model_type,status,current_version)
SELECT 820000000000000001,'SYSTEM_INBOUND',CONVERT(0xe7b3bbe7bb9fe591bce585a5 USING utf8mb4),'INBOUND','PUBLISHED',1
WHERE NOT EXISTS (SELECT 1 FROM fcc_flow_definition WHERE id=820000000000000001);
INSERT INTO fcc_flow_definition_version(id,flow_definition_id,version_no,definition_json,checksum,publish_status,published_at,created_by)
SELECT 820000000000000021,820000000000000001,1,CONVERT(0x7b22736368656d6156657273696f6e223a322c2274656d706c617465223a22494e424f554e44222c22657865637574696f6e4d6f6465223a2246495845445f52554e54494d45222c22656e747279223a22454e545259222c22737461676573223a5b22454e545259222c224d454e55222c224252414e4348222c22524f555445222c22425249444745222c22434f4e4e4543544544222c22454e44225d2c22706172616d6574657273223a7b22726f757465536f75726365223a224449445f42494e44494e47222c226d656e75536f75726365223a2250494e4e45445f464c4f575f56455253494f4e222c2271756575655365636f6e6473223a3132302c226167656e7452696e675365636f6e6473223a33302c22756e616e737765726564416374696f6e223a2243414c4c4241434b227d2c226e6f646573223a5b7b226b6579223a22454e545259222c226c6162656c223a22e591bce585a5e58f97e79086222c22616374696f6e223a225245534f4c56455f4449445f414e445f5041524b222c22696e70757473223a5b226e6f64654964222c226368616e6e656c55756964222c226469644e756d626572225d2c226f757470757473223a5b22726f757465546172676574222c22666c6f7756657273696f6e4964225d2c227472616e736974696f6e73223a5b7b227768656e223a2252454144595f414e445f4d454e555f454e41424c4544222c22746f223a224d454e55227d2c7b227768656e223a2252454144595f414e445f4d454e555f44495341424c4544222c22746f223a22524f555445227d2c7b227768656e223a22524f5554455f4e4f545f464f554e445f4f525f44455354524f59222c22746f223a22454e44227d5d7d2c7b226b6579223a224d454e55222c226c6162656c223a22e6aca2e8bf8ee8afade4b88ee68c89e994aee694b6e58fb7222c22616374696f6e223a22524541445f44544d46222c22706172616d6574657273223a7b226d696e446967697473223a312c226d6178446967697473223a312c227472696573223a312c2274696d656f7574536f75726365223a226d656e752e74696d656f75745365636f6e6473222c226d65646961536f75726365223a226d656e752e70726f6d7074222c22616374696f6e4166746572223a225041524b227d2c226f757470757473223a5b226469676974225d2c227472616e736974696f6e73223a5b7b227768656e223a2256414c49445f4449474954222c22746f223a224252414e4348227d2c7b227768656e223a2254494d454f55545f4f525f44455354524f59222c22746f223a22454e44227d5d7d2c7b226b6579223a224252414e4348222c226c6162656c223a22e68c89e994aee69da1e4bbb6e58886e694af222c22616374696f6e223a2253454c4543545f44494749545f524f555445222c22696e70757473223a5b226469676974222c226272616e63686573222c2264656661756c74526f757465225d2c226f757470757473223a5b22666c6f774272616e6368222c22726f757465546172676574225d2c227472616e736974696f6e73223a5b7b227768656e223a2244494749545f4d41544348222c22746f223a22524f555445222c22726573756c74223a224d4154434845445f4252414e4348227d2c7b227768656e223a22454c5345222c22746f223a22524f555445222c22726573756c74223a2244454641554c545f524f555445227d5d7d2c7b226b6579223a22524f555445222c226c6162656c223a22e58886e9858de5b9b6e591bce58fabe59d90e5b8ad222c22616374696f6e223a22524553455256455f414e445f4449414c5f4147454e54222c22706172616d6574657273223a7b227374726174656779223a2252454144595f554e54524945445f4147454e54222c2272696e675365636f6e6473223a33302c22717565756554696d656f7574536f75726365223a22726f7574652e71756575655365636f6e6473227d2c226f757470757473223a5b226167656e74576f726b4e6f222c226167656e744368616e6e656c55756964225d2c227472616e736974696f6e73223a5b7b227768656e223a224147454e545f5245414459222c22746f223a22425249444745227d2c7b227768656e223a224147454e545f4641494c45445f414e445f51554555455f4f50454e222c22746f223a22524f555445222c22726573756c74223a224e4558545f4147454e545f415454454d5054227d2c7b227768656e223a224e4f5f4147454e545f414e445f51554555455f4f50454e222c22746f223a22524f555445222c22726573756c74223a2257414954227d2c7b227768656e223a2251554555455f54494d454f55545f4f525f435553544f4d45525f44455354524f59222c22746f223a22454e44227d5d7d2c7b226b6579223a22425249444745222c226c6162656c223a22e6a1a5e68ea5e58f8ce696b9222c22616374696f6e223a224348414e4e454c5f425249444745222c22696e70757473223a5b226167656e744368616e6e656c55756964222c2267756573744368616e6e656c55756964225d2c227472616e736974696f6e73223a5b7b227768656e223a224252494447455f4556454e54222c22746f223a22434f4e4e4543544544227d2c7b227768656e223a2244455354524f59222c22746f223a22454e44227d5d7d2c7b226b6579223a22434f4e4e4543544544222c226c6162656c223a22e58f8ce696b9e9809ae8af9d222c22616374696f6e223a22574149545f464f525f48414e475550222c227472616e736974696f6e73223a5b7b227768656e223a2244455354524f59222c22746f223a22454e44227d5d7d2c7b226b6579223a22454e44222c226c6162656c223a22e7bb93e69d9fe4b88ee59b9ee68ba8e5a484e79086222c22616374696f6e223a2246494e414c495a455f494e424f554e44222c22706172616d6574657273223a7b2272656c656173654167656e74223a747275652c2268616e67757052656d61696e696e674c6567223a747275652c2263726561746543616c6c6261636b5768656e223a22554e414e5357455245445f414e445f43414c4c4241434b5f454e41424c4544227d2c226f757470757473223a5b2268616e6775704361757365222c226475726174696f6e222c2262696c6c736563225d2c227465726d696e616c223a747275652c227472616e736974696f6e73223a5b5d7d5d7d USING utf8mb4),'03ed555b8704fe769ec20287ab0c0f8c5bd4ee1360e786a7eaa57ea02c14a4f0','PUBLISHED',UTC_TIMESTAMP(3),'system'
WHERE NOT EXISTS (SELECT 1 FROM fcc_flow_definition_version WHERE flow_definition_id=820000000000000001 AND version_no=1);
UPDATE fcc_flow_definition SET current_version=1,status='PUBLISHED' WHERE id=820000000000000001;

INSERT INTO fcc_flow_definition(id,flow_key,flow_name,model_type,status,current_version)
SELECT 820000000000000002,'SYSTEM_AGENT_FIRST',CONVERT(0xe59d90e5b8ade58588e68ea5e590ace5a496e591bc USING utf8mb4),'AGENT_FIRST','PUBLISHED',1
WHERE NOT EXISTS (SELECT 1 FROM fcc_flow_definition WHERE id=820000000000000002);
INSERT INTO fcc_flow_definition_version(id,flow_definition_id,version_no,definition_json,checksum,publish_status,published_at,created_by)
SELECT 820000000000000022,820000000000000002,1,CONVERT(0x7b22736368656d6156657273696f6e223a322c2274656d706c617465223a224147454e545f4649525354222c22657865637574696f6e4d6f6465223a2246495845445f52554e54494d45222c22656e747279223a22454e545259222c22737461676573223a5b22454e545259222c224449414c5f4147454e54222c224449414c5f435553544f4d4552222c22425249444745222c22434f4e4e4543544544222c22454e44225d2c22706172616d6574657273223a7b226469616c5365636f6e6473223a33302c22726f757465536f75726365223a224f5554424f554e445f524f555445222c2274726967676572536f7572636573223a5b224d414e55414c222c2250524f47524553534956455f4a4f42222c2243414c4c4241434b225d7d2c226e6f646573223a5b7b226b6579223a22454e545259222c226c6162656c223a22e5a496e591bce58f97e79086222c22616374696f6e223a2256414c49444154455f524f5554455f414e445f524553455256455f4147454e54222c22696e70757473223a5b226f776e6572222c226e756d626572225d2c226f757470757473223a5b2263616c6c4964222c226167656e744368616e6e656c55756964222c2267756573744368616e6e656c55756964225d2c227472616e736974696f6e73223a5b7b227768656e223a224143434550544544222c22746f223a224449414c5f4147454e54227d2c7b227768656e223a2252454a4543544544222c22746f223a22454e44227d5d7d2c7b226b6579223a224449414c5f4147454e54222c226c6162656c223a22e58588e591bce59d90e5b8ad222c22616374696f6e223a224449414c5f4147454e54222c22706172616d6574657273223a7b2274696d656f75745365636f6e6473223a33302c2264657374696e6174696f6e536f75726365223a22424f554e445f455854454e53494f4e227d2c227472616e736974696f6e73223a5b7b227768656e223a224147454e545f5245414459222c22746f223a224449414c5f435553544f4d4552227d2c7b227768656e223a2244455354524f59222c22746f223a22454e44227d5d7d2c7b226b6579223a224449414c5f435553544f4d4552222c226c6162656c223a22e591bce58fabe5aea2e688b7222c22616374696f6e223a224449414c5f435553544f4d4552222c22706172616d6574657273223a7b2274696d656f75745365636f6e6473223a33302c2264657374696e6174696f6e536f75726365223a225245534f4c5645445f4f5554424f554e445f524f555445227d2c227472616e736974696f6e73223a5b7b227768656e223a22435553544f4d45525f5245414459222c22746f223a22425249444745227d2c7b227768656e223a2244455354524f59222c22746f223a22454e44227d5d7d2c7b226b6579223a22425249444745222c226c6162656c223a22e6a1a5e68ea5e58f8ce696b9222c22616374696f6e223a224348414e4e454c5f425249444745222c22696e70757473223a5b226167656e744368616e6e656c55756964222c2267756573744368616e6e656c55756964225d2c227472616e736974696f6e73223a5b7b227768656e223a224252494447455f4556454e54222c22746f223a22434f4e4e4543544544227d2c7b227768656e223a2244455354524f59222c22746f223a22454e44227d5d7d2c7b226b6579223a22434f4e4e4543544544222c226c6162656c223a22e58f8ce696b9e9809ae8af9d222c22616374696f6e223a22574149545f464f525f48414e475550222c227472616e736974696f6e73223a5b7b227768656e223a2244455354524f59222c22746f223a22454e44227d5d7d2c7b226b6579223a22454e44222c226c6162656c223a22e7bb93e69d9fe5a496e591bc222c22616374696f6e223a2246494e414c495a455f4f5554424f554e44222c22706172616d6574657273223a7b2272656c656173654167656e74223a747275652c2268616e67757052656d61696e696e674c6567223a747275657d2c226f757470757473223a5b2268616e6775704361757365222c226475726174696f6e222c2262696c6c736563225d2c227465726d696e616c223a747275652c227472616e736974696f6e73223a5b5d7d5d7d USING utf8mb4),'4e31748a6099cfdce9b4cd721332cc392e87706fa70adbef872e67938816ede5','PUBLISHED',UTC_TIMESTAMP(3),'system'
WHERE NOT EXISTS (SELECT 1 FROM fcc_flow_definition_version WHERE flow_definition_id=820000000000000002 AND version_no=1);
UPDATE fcc_flow_definition SET current_version=1,status='PUBLISHED' WHERE id=820000000000000002;

INSERT INTO fcc_flow_definition(id,flow_key,flow_name,model_type,status,current_version)
SELECT 820000000000000003,'SYSTEM_NOTIFICATION',CONVERT(0xe9809ae79fa5e5a496e591bc USING utf8mb4),'NOTIFICATION','PUBLISHED',1
WHERE NOT EXISTS (SELECT 1 FROM fcc_flow_definition WHERE id=820000000000000003);
INSERT INTO fcc_flow_definition_version(id,flow_definition_id,version_no,definition_json,checksum,publish_status,published_at,created_by)
SELECT 820000000000000023,820000000000000003,1,CONVERT(0x7b22736368656d6156657273696f6e223a322c2274656d706c617465223a224e4f54494649434154494f4e222c22657865637574696f6e4d6f6465223a2246495845445f52554e54494d45222c22656e747279223a22454e545259222c22737461676573223a5b22454e545259222c224449414c5f435553544f4d4552222c224e4f54494659222c22434f4e4649524d222c22454e44225d2c22706172616d6574657273223a7b226469616c5365636f6e6473223a33302c226d65646961536f75726365223a226663632e6f7574626f756e642e6e6f74696669636174696f6e2d66696c65222c22636f6e6669726d6174696f6e4469676974223a2231227d2c226e6f646573223a5b7b226b6579223a22454e545259222c226c6162656c223a22e9809ae79fa5e4bbbbe58aa1e58f97e79086222c22616374696f6e223a2256414c49444154455f4e4f54494649434154494f4e5f414e445f524f555445222c22696e70757473223a5b226f776e6572222c226e756d626572222c22617474656d70744964225d2c227472616e736974696f6e73223a5b7b227768656e223a224143434550544544222c22746f223a224449414c5f435553544f4d4552227d2c7b227768656e223a2252454a4543544544222c22746f223a22454e44227d5d7d2c7b226b6579223a224449414c5f435553544f4d4552222c226c6162656c223a22e591bce58fabe5aea2e688b7222c22616374696f6e223a224449414c5f435553544f4d4552222c22706172616d6574657273223a7b2274696d656f75745365636f6e6473223a33307d2c227472616e736974696f6e73223a5b7b227768656e223a22435553544f4d45525f5245414459222c22746f223a224e4f54494659227d2c7b227768656e223a2244455354524f59222c22746f223a22454e44227d5d7d2c7b226b6579223a224e4f54494659222c226c6162656c223a22e9809ae79fa5e694bee99fb3e4b88ee694b6e58fb7222c22616374696f6e223a22524541445f44544d46222c22706172616d6574657273223a7b226d696e446967697473223a312c226d6178446967697473223a312c227472696573223a312c2274696d656f75745365636f6e6473223a31302c22646967697454696d656f75744d73223a323030302c227465726d696e61746f7273223a2223222c227265676578223a225e5b315d24222c22616374696f6e4166746572223a2248414e475550227d2c227472616e736974696f6e73223a5b7b227768656e223a2244494749545f455155414c535f31222c22746f223a22434f4e4649524d227d2c7b227768656e223a2244455354524f595f574954484f55545f434f4e4649524d4154494f4e222c22746f223a22454e44222c22726573756c74223a22554e434f4e4649524d4544227d5d7d2c7b226b6579223a22434f4e4649524d222c226c6162656c223a22e4bf9de5ad98e5aea2e688b7e7a1aee8aea4222c22616374696f6e223a22504552534953545f434f4e4649524d4154494f4e5f414e445f48414e475550222c226f757470757473223a5b226e6f74696669636174696f6e436f6e6669726d6564225d2c227472616e736974696f6e73223a5b7b227768656e223a2244455354524f59222c22746f223a22454e44227d5d7d2c7b226b6579223a22454e44222c226c6162656c223a22e7bb93e69d9fe9809ae79fa5e9809ae8af9d222c22616374696f6e223a2246494e414c495a455f4e4f54494649434154494f4e222c226f757470757473223a5b2268616e6775704361757365222c226e6f74696669636174696f6e436f6e6669726d6564222c226475726174696f6e222c2262696c6c736563225d2c227465726d696e616c223a747275652c227472616e736974696f6e73223a5b5d7d5d7d USING utf8mb4),'6b8d2e9ae080d23a69a90810b16fa1334d89394f56cbf31c5e6241f5039480fa','PUBLISHED',UTC_TIMESTAMP(3),'system'
WHERE NOT EXISTS (SELECT 1 FROM fcc_flow_definition_version WHERE flow_definition_id=820000000000000003 AND version_no=1);
UPDATE fcc_flow_definition SET current_version=1,status='PUBLISHED' WHERE id=820000000000000003;

INSERT INTO fcc_flow_definition(id,flow_key,flow_name,model_type,status,current_version)
SELECT 820000000000000004,'SYSTEM_PHONE_BINDING',CONVERT(0xe8af9de69cbae7bb91e5ae9a USING utf8mb4),'PHONE_BINDING','PUBLISHED',1
WHERE NOT EXISTS (SELECT 1 FROM fcc_flow_definition WHERE id=820000000000000004);
INSERT INTO fcc_flow_definition_version(id,flow_definition_id,version_no,definition_json,checksum,publish_status,published_at,created_by)
SELECT 820000000000000024,820000000000000004,1,CONVERT(0x7b22736368656d6156657273696f6e223a322c2274656d706c617465223a2250484f4e455f42494e44494e47222c22657865637574696f6e4d6f6465223a2246495845445f52554e54494d45222c22656e747279223a22454e545259222c22737461676573223a5b22454e545259222c22434f4c4c4543545f434f4445222c225645524946595f42494e44494e47222c22454e44225d2c22706172616d6574657273223a7b22776f726b4e6f4d696e446967697473223a322c22776f726b4e6f4d6178446967697473223a32302c226d65646961536f75726365223a226663632e62696e64696e672e70726f6d70742d66696c65227d2c226e6f646573223a5b7b226b6579223a22454e545259222c226c6162656c223a22e8af86e588abe7bb91e5ae9ae8af9de69cba222c22616374696f6e223a2256414c49444154455f42494e44494e475f455854454e53494f4e222c22696e70757473223a5b226e6f64654964222c226368616e6e656c55756964222c22657874656e73696f6e225d2c227472616e736974696f6e73223a5b7b227768656e223a225245414459222c22746f223a22434f4c4c4543545f434f4445227d2c7b227768656e223a22494e56414c49445f4f525f44455354524f59222c22746f223a22454e44227d5d7d2c7b226b6579223a22434f4c4c4543545f434f4445222c226c6162656c223a22e694b6e58f96e59d90e5b8ade5b7a5e58fb7222c22616374696f6e223a22524541445f44544d46222c22706172616d6574657273223a7b226d696e446967697473536f75726365223a226663632e62696e64696e672e776f726b2d6e6f2d6d696e2d646967697473222c226d6178446967697473536f75726365223a226663632e62696e64696e672e776f726b2d6e6f2d6d61782d646967697473222c227472696573223a312c2274696d656f75745365636f6e6473223a36302c22646967697454696d656f75744d73223a31303030302c227465726d696e61746f7273223a2223222c227265676578223a225e5b302d395d2b24227d2c227472616e736974696f6e73223a5b7b227768656e223a224449474954535f5245434549564544222c22746f223a225645524946595f42494e44494e47227d2c7b227768656e223a2244455354524f59222c22746f223a22454e44227d5d7d2c7b226b6579223a225645524946595f42494e44494e47222c226c6162656c223a22e6a0a1e9aa8ce5b9b6e7bb91e5ae9a222c22616374696f6e223a2242494e445f4147454e545f455854454e53494f4e222c22706172616d6574657273223a7b226d6174636841757468656e74696361746564457874656e73696f6e223a747275652c226c6f636b4167656e74416e64457874656e73696f6e223a747275652c227065727369737442696e64696e67486973746f7279223a747275657d2c226f757470757473223a5b2262696e64696e674163636570746564225d2c227472616e736974696f6e73223a5b7b227768656e223a2256414c4944222c22746f223a22454e44222c22726573756c74223a22424f554e44227d2c7b227768656e223a22454c5345222c22746f223a22454e44222c22726573756c74223a2252454a4543544544227d5d7d2c7b226b6579223a22454e44222c226c6162656c223a22e7bb93e69d9fe7bb91e5ae9ae9809ae8af9d222c22616374696f6e223a2248414e4755505f42494e44494e475f4348414e4e454c222c227465726d696e616c223a747275652c227472616e736974696f6e73223a5b5d7d5d7d USING utf8mb4),'26c879278320c0930aaac70e718b3beed40aca807c7a6e5e385a122fc7240d07','PUBLISHED',UTC_TIMESTAMP(3),'system'
WHERE NOT EXISTS (SELECT 1 FROM fcc_flow_definition_version WHERE flow_definition_id=820000000000000004 AND version_no=1);
UPDATE fcc_flow_definition SET current_version=1,status='PUBLISHED' WHERE id=820000000000000004;

COMMIT;
-- END GENERATED COMPLETE SYSTEM MODELS
